### ISSUE TITLE
Clicks should toggle between on/off, but enters on state just once

### ISSUE THREAD

**Issue by Earthwings** [domoritz/leaflet-locatecontrol#1]
Thanks for the control, nice work.

When clicking on the icon once, it activates the location search. Another click deactivates it. I'd expect subsequent clicks on it to activate it again, but that's not the case here. I believe this is because map.locate() does not generate more onLocationFound events after the first one.

In practice this means that (with autoRemoveCircle=true) the location circle is shown after the first click, but then never again after one and more clicks.

**Comment by domoritz** [comment]
Thanks. Should be fixed in 6f0d6c17ade1ede0c4540e20c2593f52c223c.

**Comment by Earthwings** [comment]
Yes, works fine now. Thanks.
