### ISSUE TITLE
Add ability to specify layer where to add circleLayer

### ISSUE THREAD

**Issue by ghost** [domoritz/leaflet-locatecontrol#100]
For example, I'd like to add functionality "on my location click". Then I would be using geometry from current location displayed on the map.

Or maybe there's another solution?

**Comment by domoritz** [comment]
This will be possible to do ofter #96 is merged, I guess.

**Comment by domoritz** [comment]
You can extend the locate control easily now. Check out https://github.com/domoritz/leaflet-locatecontrol#extending
