### ISSUE TITLE
AMD support

### ISSUE THREAD

**Issue by ilvalle** [domoritz/leaflet-locatecontrol#103]
Something similar to what has been already done in leatflet, see https://github.com/Leaflet/Leaflet/issues/1364

**Comment by domoritz** [comment]
Could you send a pr for that?

**Comment by ilvalle** [comment]
see https://github.com/domoritz/leaflet-locatecontrol/pull/104

**Comment by marekkalnik** [comment]
Shouldn't this be closed? ;)
