### ISSUE TITLE
Handling locate button click when following is disabled

### ISSUE THREAD

**Issue by mandrek44** [domoritz/leaflet-locatecontrol#106]
Currently, when I initialize the control with `follow` option disabled:

```
        lc = L.control.locate({
            follow: false
        }).addTo(map);
```

I can't add handler that will be called when locate button is clicked. The "startfollowing" event is not fired in this case. 

Is there any way I can handle the button click?

**Comment by domoritz** [comment]
There is not from the plugin but you can add a click handler yourself with something like

``` js
lc = L.control.locate({
    follow: false
}).addTo(map);
lc._link.onclick = function(){console.log("click");}
```

It's a bit hacky, though.
