### ISSUE TITLE
Last update broke things?

### ISSUE THREAD

**Issue by isc-rsingh** [domoritz/leaflet-locatecontrol#111]
My app broke after the latest code update. The error I get is:
"TypeError: lc.locate is not a function"
Did something change?

**Comment by gmccrackin** [comment]
Yes. The locate function no longer exists. You want `lc.start()`.

https://github.com/domoritz/leaflet-locatecontrol#methods

**Comment by domoritz** [comment]
Yes, sorry. Many things changed in the last release. I may release a stable version 1.0 in a few months but right now nothing is guaranteed to be stable.

**Comment by gmccrackin** [comment]
@domoritz It might be a good idea to put a breaking change notice at the top of the readme.

**Comment by isc-rsingh** [comment]
+1 on the breaking change notice. And thanks @domoritz for the great plugin!
