### ISSUE TITLE
Non minified version of the dist files

### ISSUE THREAD

**Issue by trygve-lie** [domoritz/leaflet-locatecontrol#112]
Would it be possible to add a non minified version of the distribution files in the dist folder when releasing?

**Comment by domoritz** [comment]
You used to just take the files `src` but I switched over to scss. Can you add a build step to the grunt file? I'm happy to review and merge.

**Comment by trygve-lie** [comment]
Thanks for fixing this. Sorry I did'nt find time to provide a pull request before you fixed it.
