### ISSUE TITLE
onLocationError and onLocationOutsideMapBounds execute an alert()

### ISSUE THREAD

**Issue by trygve-lie** [domoritz/leaflet-locatecontrol#113]
I see that [onLocationError](https://github.com/domoritz/leaflet-locatecontrol/blob/gh-pages/src/L.Control.Locate.js#L64) and [onLocationOutsideMapBounds](https://github.com/domoritz/leaflet-locatecontrol/blob/gh-pages/src/L.Control.Locate.js#L72) execute an `alert()`. 

Is this really desired behavior?

From a library point of view, would it not be better if those where emitted events the user can attach their own event listeners on?

**Comment by domoritz** [comment]
Those functions are just the default options, which can be easily overridden. Just pass your own function.

And yes, events would be better and there were some discussions about this in #72 but I never got round to replace the functions with events. Should be easy, though. Do you want to send a pull request?

**Comment by trygve-lie** [comment]
I can take a stab at a pull request :)

**Comment by domoritz** [comment]
I look forward to it.

**Comment by domoritz** [comment]
Closing for now.
