### ISSUE TITLE
Resetting of the Control Icons on Location Error

### ISSUE THREAD

**Issue by schulzj01** [domoritz/leaflet-locatecontrol#114]
Using the current version of the plugin, if I hit a locationerror event, the control keeps spinning.  To me this is telling the user that the location hasn't been found yet.  Also, if I want to call a locate.stop(), I would want the spinning to stop as well.  I would suggest adding this into _cleanClasses:

```
 L.DomUtil.removeClasses(this._icon, this.options.iconLoading);   
 L.DomUtil.addClasses(this._icon, this.options.icon);
```

This way it resets the icon back to it's original state when the classes are cleaned.  Also, when a locationerror is called, I would think a better approach would be to call stop() instead of _deactivate().  This would call _cleanClasses again to reset spinning icon.

Just some thoughts from a first time user that might help.

Great work on this.  Thanks!

**Comment by domoritz** [comment]
What browser do you use? What error do you mean?

I just tried it with denying location access and it worked fine. The spinner stopped spinning.

**Comment by domoritz** [comment]
Ahh, I think I know what happened. The problem only occurred if following was false.

**Comment by schulzj01** [comment]
Now that is some quick service :-)  Thanks again for your plugin!
