### ISSUE TITLE
Bower/CommonJS dependency on leaflet.js breaks when using with mapbox.js

### ISSUE THREAD

**Issue by chadwilcomb** [domoritz/leaflet-locatecontrol#115]
It seems that if you are using this plugin via a CommonJS require, the Bower packaged version will add leaflet.js as a dependency on load. 

``` javascript
    // define a Common JS module that relies on 'leaflet'
    } else if (typeof exports === 'object') {
        module.exports = factory(require("./..\\..\\leaflet\\dist\\leaflet.js"));
    }
```

Because I am using mapbox.js instead of leaflet.js, the leaflet.js API blows out the mapbox API (e.g- `L.mapbox` is now undefined). Can you define the CommonJS `module.exports` so that it does not inject the leaflet dependency? I think it can be reasonably assumed that if you are using something called leaflet-locatecontrol plugin, you will have leaflet.js (or mapbox.js) already loaded in your page.

Thank you for creating this plugin, it is a very useful abstraction!

**Comment by domoritz** [comment]
What about just removing leaflet as a dependency from the bower file?  Would you mind sending a pr?

**Comment by chadwilcomb** [comment]
Interestingly, I just happened to be looking through the [Backbone.js source code](http://backbonejs.org/docs/backbone.html#section-5) today and they do the same thing with the Underscore.js dependency, so maybe this is the appropriate aproach. Maybe I should fork your project and modify with a dependency on mapbox.js instead (or no dependency at all). I'm new to open source collaboration so not sure when you make that sort of decision. I welcome anyone's feedback on this.

**Comment by domoritz** [comment]
I'm not a fan of fragmentation and would be okay with removing the bower dependency. Just send me a pull request.

**Comment by chadwilcomb** [comment]
If I just remove the dependency from bower.json, but continue to inject the leaflet require into the factory method, I will still have the same issue as leaflet is already loaded into my application as a dependency of mapbox.js. 

I feel like the problem actually falls more on how mapbox.js works for CommonJS style modules, where it uses the global L variable to latch on to. See this [issue](https://github.com/mapbox/mapbox.js/issues/726)

I was able to resolve the problem by just checking for the global L variable and falling back to the require('leaflet'), like this:

``` javascript
    module.exports = factory(L || require('leaflet'));
```

Not sure how you feel about that solution. I guess this might be better?

``` javascript
    // define a Common JS module that relies on 'leaflet'
    } else if (typeof exports === 'object') {
        if (typeof window !== 'undefined' && window.L) {
            module.exports = factory(L);
        } else {
            module.exports = factory(require('leaflet'));
        }
    }
```

**Comment by gmccrackin** [comment]
I really like that solution @chadwilcomb. It would also solve some small problems I am having with some of the other plugins that latch on to the global L.

**Comment by chadwilcomb** [comment]
I created a pull request for this change, in case @domoritz thinks it a good solution.

**Comment by domoritz** [comment]
Awesome. I'll check out the pr and merge if it's working for me. Btw @chadwilcomb I don't see a pr yet.

**Comment by chadwilcomb** [comment]
Oops. @domoritz I had created the pull request on my own fork. You should see it now: https://github.com/domoritz/leaflet-locatecontrol/pull/116
