### ISSUE TITLE
Styling issue

### ISSUE THREAD

**Issue by besi** [domoritz/leaflet-locatecontrol#118]
I did include the control like described on the website

Now the icon seems to be too small and with the standard buttons the icons aren't visible.

![screen shot 2015-03-05 at 21 01 42](https://cloud.githubusercontent.com/assets/160412/6513382/e098dc1c-c37a-11e4-9d0f-816369a4af47.png)

**Comment by domoritz** [comment]
Why are your buttons dark? You must have some other style sheet.

**Comment by besi** [comment]
I am using the default but maybe some of my other CSS overrides the default mapbox CSS. I will check this.

**Comment by gamecubate** [comment]
<bump> on this. Similar problem + 1 more:
- icon not visible (same as above)

After adding font-awesome lib, icon appears but:
- icon is off center
- "locating" animation (rotation css) is off-center.

**Comment by domoritz** [comment]
Do you use a custom css or mapbox?

**Comment by gamecubate** [comment]
mapbox (per https://www.mapbox.com/mapbox.js/plugins/#leaflet-locatecontrol, the demo of which fails to work btw, with console reporting failure for "GET https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.42.0/L.Control.Locate.js").

**Comment by domoritz** [comment]
@gamecubate Yes, the files are not deployed correctly by mapbox. See https://github.com/mapbox/mapbox.js-plugins/issues/25. I'd suggest that you use bower, if you can. It makes sure you always use the latest version.

To fix the style issue, use the special [mapbox css file](https://github.com/domoritz/leaflet-locatecontrol/blob/gh-pages/dist/L.Control.Locate.mapbox.css) that I build. It resolves this style issue.

**Comment by gamecubate** [comment]
Thanks. Will try with bower.

**Comment by domoritz** [comment]
Reopen if this is still an issue.
