### ISSUE TITLE
location based only on gps data

### ISSUE THREAD

**Issue by c1p81** [domoritz/leaflet-locatecontrol#120]
I'm trying to write a simple application with offline maps for hiking 
On the map i have a gps track and i would like to use your plugin to show the user position

all works fine when i have data connection but if i select "airplane mode" (or if i deselect internet data link........in mountain the gsm network it's not always available) i can't get or update the position 

it's possible to have the lat,lon user position based only on gps data???
if not, there is a possible solution inside leaflet??

thank you for your job

Luca

**Comment by domoritz** [comment]
How would you get map tiles without internet?

**Comment by c1p81** [comment]
it's quite possible (set a local folder with downloaded png files with MOBAC  instead a web link as source)
i need offline maps because i'm developing an phonegap app for hiking where  i don't have data connection (in same places i dont have phone connection)

i have found a solution with this plugin
http://labs.easyblog.it/maps/leaflet-gps/
not listed in the official plugin page

thank you 
best regards

Luca

**Comment by domoritz** [comment]
Okay, I looked at the source code of the plugin you mentioned. There is nothing specific for gps and you can use my control. The only thing you may want to do, is pass `enableHighAccuracy: true` to `locateOptions` as described in https://github.com/domoritz/leaflet-locatecontrol/blob/gh-pages/README.md. This should use GPS, if available.

**Comment by domoritz** [comment]
If that works, I'll add a note to the readme. @c1p81 could you tell me whether it worked?
