### ISSUE TITLE
Consider cdn.rawgithub.com

### ISSUE THREAD

**Issue by zbycz** [domoritz/leaflet-locatecontrol#127]
Hi,

consider offering your users link such as
https://cdn.rawgit.com/domoritz/leaflet-locatecontrol/v0.43.0/dist/L.Control.Locate.min.js

instead of 
`<script src="//rawgithub.com/domoritz/leaflet-locatecontrol/gh-pages/dist/L.Control.Locate.min.js" ></script>`. But careful once a branch URL is accessed via cdn.rawgithub, it never expires. See https://rawgit.com/ for details.

Kind regards,
Pavel

**Comment by domoritz** [comment]
Raw github is only for testing and I don't want to maintain bower, npm and rawgit. If you set up the deploy script in a way that it automatically updates the readme, I'd merge. For now this is too many things to support.
