### ISSUE TITLE
Get coordinates on locateOnNextLocationFound

### ISSUE THREAD

**Issue by dietah** [domoritz/leaflet-locatecontrol#130]
Hi,

Is there a possibility to retrieve the coordinates of a new location after `lc.start()` is triggered without having to extract the center point?

It would be handy if an event is triggered every time a new location is found with the object of the new location. Or I am overlooking this feature?

Thanks,
Dieter

**Comment by dietah** [comment]
Hi,

In the meantime I have found a solution via the LeafletJs `Locationfound` event.

Thanks,
Dieter

**Comment by domoritz** [comment]
Yeah, just subscribe to the `locationfound` even on map. No need to use this plugin.
