### ISSUE TITLE
{lat} {long}

### ISSUE THREAD

**Issue by reyemtm** [domoritz/leaflet-locatecontrol#139]
I have the following:

```
            var distance, unit, lt;
            if (this.options.metric) {
                distance = radius.toFixed(0);
                unit = "meters";
                lat = this._event.latitude;
                long = this._event.longitude;
            } else {
                distance = (radius * 3.2808399).toFixed(0);
                unit = "feet";
                lat = this._event.latitude;
                long = this._event.longitude;
            }
```

in or around line 207. I use these values in the map for filling out a form with gps coordinates. Were these ever in your code? Not sure at this point if I added it or they were removed from your code at some point.

**Comment by domoritz** [comment]
We now use `this._event.latlng`. If you want the location, subscribe to the `locationfound` event on the map.
