### ISSUE TITLE
Setting drawCircle: false seems to break zoom on location found

### ISSUE THREAD

**Issue by giolari** [domoritz/leaflet-locatecontrol#141]
Setting drawCircle:false seems to break the zoom-in on user position on location found.
Simply:

```
lc = L.control.locate({
    follow: true,
    strings: {
        title: "Show me where I am, yo!"
    }
}).addTo(map);

it's ok.

lc = L.control.locate({
    follow: true,
    drawCircle: false,
    strings: {
        title: "Show me where I am, yo!"
    }
}).addTo(map);
```

stop zooming on user position (tested with LC version 0.44 +leaflet 0.7.5 on Chrome and Firefox)

**Comment by domoritz** [comment]
Hmm, for some reason we added a condition in https://github.com/domoritz/leaflet-locatecontrol/blob/8f165054a0b982587c7c811e9bc3957257306a39/src/L.Control.Locate.js#L172.
