### ISSUE TITLE
Uncaught Error: Invalid LatLng object: (40.7999350265614, NaN)

### ISSUE THREAD

**Issue by endigo** [domoritz/leaflet-locatecontrol#143]
I'm getting this error when I call start() function.

``` javascript
   var locate = new new L.control.locate({
        keepCurrentZoomLevel: true,
        locateOptions: {
            enableHighAccuracy: true,
            maxZoom: 16,
        },
   });

  setTimeout(function(){
     locate.start();
  }, 500);
```

Then error occurs, my map won't drawing and zoom level is undefined.

```
https://map.minu.mn/beta/#/?c=47.9131:106.9359:undefined
```

I'm using:
"angular": "^1.4.5",
"angular-leaflet-directive": "^0.8.8",
"leaflet": "^0.7.5",
"leaflet.locatecontrol": "^0.44.0",

**Comment by domoritz** [comment]
You have to add the control to the map. Also, don't call new on the function that returns the control.

`var locate = L.control.locate().addTo(map)`
