### ISSUE TITLE
L.control.locate is not a function

### ISSUE THREAD

**Issue by adhithyaraja** [domoritz/leaflet-locatecontrol#147]
Hi,
I'm getting the error like L.control.locate is not a function.Please help where I'm going wrong. Thanks in advance.
My code is

```
map.L.control.locate({
       setView: true,
       drawCircle: true,
       markerClass: L.circleMarker
     }).addTo(map);
```

**Comment by domoritz** [comment]
Did you include the javascript source file? If yes, can you try to upload a small example where you see that problem to https://jsfiddle.net/?

**Comment by domoritz** [comment]
Maybe look at how I set up the demo at https://github.com/domoritz/leaflet-locatecontrol/blob/gh-pages/demo/index.html. Let me know if it doesn't work.

**Comment by hb0u** [comment]
@domoritz , Getting the same error. Please refer to this example.
https://stackblitz.com/edit/leaflet-tfxhjh
