### ISSUE TITLE
Option to move marker for location tracking

### ISSUE THREAD

**Issue by kentr** [domoritz/leaflet-locatecontrol#149]
I need a map that follows the user's position on the map without panning the map.  I've had good results with custom code that sets the marker lat / lon in `onLocationFound`.

Would a PR for this feature be welcome?  Perhaps a new option such as `keepCurrentMapBounds` that flags whether `drawMarker()` should `panTo` or instead simply move the marker position?

**Comment by domoritz** [comment]
`setView:false` should already do that. Please let me know if it is not working. 

Or is the difference that you want the map to pan/zoom when the use is first located but not when the location updates? If that's the case, that would definitely be a welcome option. How about you change the `setView` option to take a string `always`, `onLocate`, `never` instead of adding another boolean?

**Comment by kentr** [comment]
Yes, more the latter.  I want the user to be able to pan the map and then keep the current bounds instead of having the map automatically pan back to the current location.  

How does this sound?:
1. `setView` can be `[always | untilPan | false]` (or `[always | untilPan | never]` if you prefer).
2. If `setView == untilPan`:
   - The default behavior of keeping the current location at the map center continues until the user pans the map.
   - Once the user pans the map, the object gets a new second state (something like `_userPanned`)
   - So, if `setView == untilPan && _userPanned == true`, it doesn't `panTo` for new location events.
   - If the user clicks the locate button again, `_userPanned` is reset to `false` and the default behavior renews.

**Comment by domoritz** [comment]
Oh, I used to have an option for something similar. You can find it in the readme `stopFollowingOnDrag`. The difference is that this option also disabled following completely. 

You can get the same behavior with

``` js
var lc = L.control.locate().addTo(map);
map.on('dragstart', lc._stopFollowing, lc);
```

But what you are proposing makes way more sense. The user location keep updating but the map just doesn't pan. In addition to what you proposed, the `followMarkerStyle`/`followCircleStyle` should toggle with `markerStyle`/`circleStyle`. The idea is that the user needs some visual feedback that tells them whether the map will take them out of their current location or not. I also think that `untilPan` should be the default behavior. 

Fantastic! Do you mind sending a pr along? This might actually simplify some code. Don't be afraid to change some existing behavior.

**Comment by domoritz** [comment]
@kentr Are you working on this? I'm happy to review a pr from you for this feature.

**Comment by kentr** [comment]
Yes, I'm hoping to get a PR out soon.
