### ISSUE TITLE
onLocationFound ?

### ISSUE THREAD

**Issue by nopmop** [domoritz/leaflet-locatecontrol#150]
Hello, 

sorry for the question: how to get the location after it's found?
I can't see any `onLocationFound` or `onSuccess` event in the options.

Thanks a lot :)

**Comment by nopmop** [comment]
Sorry, nevermind.
I just spot the `locationfound` in the Leaflet events. 

I was caught off guard since `onLocationError` can be specified in the options of this package.

Thank you.

**Comment by domoritz** [comment]
The reason is that I want to specify a default callback for errors but you should be able to override it.
