### ISSUE TITLE
Geolocation Error 404

### ISSUE THREAD

**Issue by johnolos** [domoritz/leaflet-locatecontrol#154]
I'm experiencing issues that came about 1-2 weeks ago without any changes on my part.

I checked mapbox example to see if they had the same error, and it does.
https://www.mapbox.com/mapbox.js/example/v1.0.0/leaflet-locatecontrol/

> www.mapbox.com says:
> Geolocation error: Network location provider at 'https://www.googleapis.com/':
> Returned error code 404..

It works on mobile, just not on Chrome v49.0.2623.87 (64-bit).
Mozilla Firefox complains with the following error:

> Geolocation error: Unknown error acquiring position.

**Comment by domoritz** [comment]
Hmm, I'm on 49.0.2623.75 beta (64-bit) and it works fine. 

Can you try http://domoritz.de/leaflet-locatecontrol/demo/

**Comment by johnolos** [comment]
Exactly the same error message. Same on Firefox.

**Comment by domoritz** [comment]
Very odd. I tried it in Firefox, Chrome, and Safari. Can you try to debug a bit? I would love to fix it but can't reproduce the issue.

**Comment by johnolos** [comment]
Sure. Let me know what you what me to.

**Comment by domoritz** [comment]
Can you look into the console when the error happens? What are the exact conditions? Can you reproduce this issue with just leaflet's http://leafletjs.com/reference.html#map-locate?

**Comment by rossanag** [comment]
Maybe it's a bit late but I faced the same using Firefox and solved in this way.
1- go to about:config
2- change the geo.wifi.uri value to https://location.services.mozilla.com/v1/geolocate?key=test

Hope it helps

**Comment by AdnanHodzic** [comment]
I ran into similar/same problem on Firefox 78 (Ubuntu 20.04), while I don't have this problem Chrome 84.

```
Error: Geolocation error: Unknown error acquiring position.
```
What fixed it for me is to go to: `about:config`

find:
`geo.provider.network.url`

change:
`https://www.googleapis.com/geolocation/v1/geolocate?key=%GOOGLE_LOCATION_SERVICE_API_KEY%`

to:
`https://location.services.mozilla.com/v1/geolocate?key=%MOZILLA_API_KEY%`
