### ISSUE TITLE
Tag 0.48.0 does not contain the code from commit 0.48.0

### ISSUE THREAD

**Issue by Maistho** [domoritz/leaflet-locatecontrol#155]
So for some reason the 0.48.0 tag does not contain all the changes in the version 0.48.0 commit... :confused:
I guess something got lost there.

**Comment by domoritz** [comment]
Yeah, I will have to fix that immediately. Thanks for reporting.

<img width="573" alt="screen shot 2016-03-14 at 13 31 28" src="https://cloud.githubusercontent.com/assets/589034/13758937/303aee82-e9e9-11e5-8dac-8e7e5ff0f997.png">

**Comment by domoritz** [comment]
I didn't know that git does not change the tag pointer when I amend a commit.

**Comment by Maistho** [comment]
Thanks for the swift response! :smile:
