### ISSUE TITLE
'startfollowing' never appears to fire when locate button is clicked

### ISSUE THREAD

**Issue by JamesLMilner** [domoritz/leaflet-locatecontrol#156]
Hi there, thanks for your hard work and great project. I am having some trouble getting the latest version to get the startfollowing event to fire. For example:

``` javascript
map.on('startfollowing', function() { 
  console.log("following");
});
```

The console.log never appears to get fired after requesting the location. Is this a known issue? I've tested in latest Chrome and Safari.

**Comment by domoritz** [comment]
Did it work?

**Comment by JamesLMilner** [comment]
No it didn't unfortunately, but I found the 'locationfound' event which did what I was looking for. I understand these are native events in Leaflet, but I might make a pull request documenting them in the  README if you also think it would be helpful for people using the plugin?

**Comment by domoritz** [comment]
That would be great. I'd say let's reference the leaflet docs where possible rather than copying, though.
