### ISSUE TITLE
Size of the round locate

### ISSUE THREAD

**Issue by hellfish2** [domoritz/leaflet-locatecontrol#159]
It's any way to set the size of the round ??? anything ??

**Comment by domoritz** [comment]
Can you send a screenshot of what you mean? You can change the size of the inner circle as well as the style with https://github.com/domoritz/leaflet-locatecontrol/blob/gh-pages/src/L.Control.Locate.js#L42. However, the outer circle shows the accuracy and you obviously cannot change the size of that.
