### ISSUE TITLE
Initialize locate on page load

### ISSUE THREAD

**Issue by bmcbride** [domoritz/leaflet-locatecontrol#16]
Is there any way to have this activated already when the page is loaded? I'd like to have this in a "pressed" state so that it zooms to the user's location automatically once the page loads and they can click it to deactivate. Thanks!

**Comment by domoritz** [comment]
With the latest version you just need to call `map.locate()` somewhere and it will automatically do the rest for you.

**Comment by bmcbride** [comment]
Thanks for responding so quickly! I gave it a try and it now errors when you toggle the control "off". Try deactivating the control and you get the following error message on line 146 of L.Control.Locate.js:

Uncaught TypeError: Object [object Object] has no method 'resetVariables'

**Comment by domoritz** [comment]
@bmcbride My mistake. Can you try it again?

**Comment by bmcbride** [comment]
Working great now- thanks!

**Comment by bmcbride** [comment]
This doesn't seem to be working anymore in the latest version. Calling map.locate() does not activate this like it used to.

**Comment by domoritz** [comment]
Yes, I had to do this because otherwise delayed events trigger a visualization which was very bad for usability. I will submit a patch in a minute that allows you to call `locate` on the control instead of the map. Sorry for the inconvenience.

**Comment by bmcbride** [comment]
Thanks!
