### ISSUE TITLE
No works in mobile chrome

### ISSUE THREAD

**Issue by dejoramo** [domoritz/leaflet-locatecontrol#166]
Profit not run the plugin "control-locate" with google chrome browser.
Someone knows the solution?

**Comment by domoritz** [comment]
I just tested it and it works. Please provide more details.

**Comment by dejoramo** [comment]
ANDROID CHORME BROWSER (DEVICE: ASUS ZENFONE 2)
Geolocation: Only secure origins are allowed (see: httpps://goo.gl/Y0ZkNV)

**Comment by domoritz** [comment]
You have to use https. See https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only?hl=en

**Comment by dejoramo** [comment]
THANKS!!!!!!!!!!!!!!!!! ;)  
Solved.
