### ISSUE TITLE
link DEMO Error

### ISSUE THREAD

**Issue by dejoramo** [domoritz/leaflet-locatecontrol#167]
it does not work:
https://domoritz.github.io/leaflet-locatecontrol/demo/

index.html files do not work the examples

**Comment by dejoramo** [comment]
DO NOT WORK THE EXAMPLES:
demo
demo 1.0
demo_mapbox

**Comment by domoritz** [comment]
Can you provide some more details? It works fine for me.

**Comment by dud3** [comment]
It doesn't work.

![leaflet-location-001](https://cloud.githubusercontent.com/assets/5823644/16522153/2a8daf3e-3f9c-11e6-83fd-122a25e5e8df.png)
![leaflet-location-002](https://cloud.githubusercontent.com/assets/5823644/16522154/2aa7056a-3f9c-11e6-80d6-2980a3843776.png)

**Comment by dud3** [comment]
cc: @domoritz

**Comment by domoritz** [comment]
Hmm, interesting. I don't see that message. What browser and OS are you using? Can you try a different browser? Does it also happen in private mode?

**Comment by dud3** [comment]
I'm on chromium `Version 53.0.2753.0 (64-bit)` - Windows 10.

It does seem to work on `firefox`.

**Comment by dud3** [comment]
@domoritz Any news over here?

**Comment by domoritz** [comment]
I just tried it on chrome (53.0.2785.34 beta-m (64-bit)) and edge on windows 10 and it worked fine. Can you try whether geolocation works on your computer at https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation

**Comment by dejoramo** [comment]
it does not work in chrome mobile

![screenshot_2016-08-02-20-02-48](https://cloud.githubusercontent.com/assets/19858449/17339514/91a6a1a8-58ec-11e6-9ed0-77d0c2ca21c5.jpg)

**Comment by domoritz** [comment]
@dejoramo You have to use https. See https://github.com/domoritz/leaflet-locatecontrol/issues/166

**Comment by domoritz** [comment]
Closing this for now. Please reopen if you think this is an issue with the plugin and not the location API.

**Comment by dud3** [comment]
@domoritz Do we mean the domain has to be on `https`?

Such as:
https://domoritz.github.io/leaflet-locatecontrol/demo/ 

Instead of:
http://domoritz.github.io/leaflet-locatecontrol/demo/

**Comment by domoritz** [comment]
In general, yes. But your browser should redirect you to https.

**Comment by dud3** [comment]
But shouldn't the demo work on `https`: https://domoritz.github.io/leaflet-locatecontrol/demo/ then?

Am I missing a point?

**Comment by dud3** [comment]
I still get the same error as in: https://github.com/domoritz/leaflet-locatecontrol/issues/167#issuecomment-229939813

**Comment by domoritz** [comment]
@dud3 You're completely right. It should work but from the error message it looks like it's not an issue with my plugin but instead the location API. This is why I suggested that you try https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation and see whetehr you get the same error.

**Comment by dud3** [comment]
@domoritz I see, but I've also told the browser to allow sharing my location, but still got the same error.

**Comment by dud3** [comment]
Hmm, strange, actually even google maps can't find my location, even though I've allowed it.

**Comment by domoritz** [comment]
That's very odd indeed but then definitely unrelated to this plugin.
