### ISSUE TITLE
"maximumAge" not working

### ISSUE THREAD

**Issue by ppete2** [domoritz/leaflet-locatecontrol#173]
Hello,
I want my accurate location on the map being updated every 10 seconds using GPS. Therefor I used the following code:

`map.locate({setView: true, watch: true, timeout:30000, maximumAge:10000, enableHighAccuracy: true});`

But the location is not updated every 10 seconds, but every 1 second. So the "maximumAge"-option seems to be ignored when using "watch: true" and "enableHighAccuracy: true". Or am I missunderstanding Leaflet's "maximumAge"-option?

Leaflet's docu writes: _"maximumAge = Maximum age of detected location. If less than this amount of milliseconds passed since last geolocation response, locate will return a cached location."_

**Comment by domoritz** [comment]
I'm not sure what the `maximumAge` is supposed to do. Can you try what Leaflet does when you call `locate` directly on the `map`?

**Comment by ppete2** [comment]
It's neither an issue of leaflet-locatecontrol nor from Leaflet, since Leaflet's location methods are just "a simple wrapper" around the standard location methods of HTML5/Javascript.

Writing a testscript and using just these HTML5-location methods (without Leaflet) produced exactly the same behaviour when "enableHighAccuracy: true" and GPS is on and receiving satellite data. (location is updated each second although "maximumAge:10000"). 
Interesting is if GPS isn't receiving satelllite data (cause phone being inside house), then position is updated just every 10 seconds!

**Comment by domoritz** [comment]
Thanks for the clarification. I'll close this issue then as it's clearly not something my code has control over.
