### ISSUE TITLE
option for bundling without Leaflet

### ISSUE THREAD

**Issue by hanbyul-here** [domoritz/leaflet-locatecontrol#174]
Hi. 

 We are writing Leaflet plugin which has leaflet-locatecontrol inside. We are offering a version with embedded Leaflet, but also offering standalone version without Leaflet. While building standalone version with [Browserify Shim](https://github.com/thlorenz/browserify-shim), I noticed that Locate Control always tries to bundle with Leaflet. (In case it helps, [this](https://github.com/mapzen/mapzen.js/blob/master/package.json#L16) is how we are building standalone version) 

I wonder there is any options not to bundle with Leaflet that I didn't notice ?

**Comment by domoritz** [comment]
I guess I could remvoe leaflet from the dependencies. I think it makes sense. What do you think?

**Comment by hanbyul-here** [comment]
I agree with removing Leaflet as a required dependency. Especially considering v1.0 of Leaflet, and needs to use the plugin with their own Leaflet version for various reasons.

**Comment by domoritz** [comment]
Done and released.
