### ISSUE TITLE
decrease current location interval

### ISSUE THREAD

**Issue by kaio328** [domoritz/leaflet-locatecontrol#176]
Is there any option to decrease the update interval of users current position?

the current interval has an unsmooth view and updates way to late.

**Comment by domoritz** [comment]
I use the leaflet locate API (http://leafletjs.com/reference-1.0.0.html#map-locate), which in turn uses your browser's API. I don't think there is any way to get more frequent updates.

**Comment by kaio328** [comment]
there is!
just add this:       enableHighAccuracy: true

boosted locating time, accuracy and updating time of current position!

works well for my mobile application

**Comment by domoritz** [comment]
Awesome! Just for the record, you can pass that option in the control

```js
L.control.locate({
    locateOptions: {
        enableHighAccuracy: true
    }).addTo(map);
```
