### ISSUE TITLE
Spinner

### ISSUE THREAD

**Issue by kaio328** [domoritz/leaflet-locatecontrol#177]
Hey again,

would like to have the spinner not only on the first locating process but everytime i cancel the locating (to normal/black icon) and then restart it. any idea?

**Comment by domoritz** [comment]
Don't you already have a location in that case?

**Comment by kaio328** [comment]
might be but would like to have it this way for "style" purposes.

how to change ur code to get that spinner for every locating process?

**Comment by domoritz** [comment]
I added a new option `cacheLocation`, which you have to set to false.
