### ISSUE TITLE
time out errormsg

### ISSUE THREAD

**Issue by kaio328** [domoritz/leaflet-locatecontrol#178]
hello again,

how to add a timeout - for example after 10 seconds - and a timeout errormsg to the locating process?

**Comment by domoritz** [comment]
You can pass locate options through to Leaflet and then use http://leafletjs.com/reference-1.0.2.html#locate-options

**Comment by domoritz** [comment]
Similar to https://github.com/domoritz/leaflet-locatecontrol#how-do-i-set-the-maximum-zoom-level
