### ISSUE TITLE
Breaking change with default settings

### ISSUE THREAD

**Issue by atodd-geoplan** [domoritz/leaflet-locatecontrol#182]
Is this a Leaflet 1.0.3 breaker perhaps? I had to change

` this._circle.setLatLng(latlng).setRadius(radius).setStyle(style);`

beacuse _circle.setLatLng returns undefined, to:

```
this._circle.setLatLng(latlng);
this._circle.setRadius(radius);
this._circle.setStyle(style);
```

**Comment by domoritz** [comment]
How can I reproduce this issue? I just updated leaflet to 1.0.3 and everything works as far as I can tell.

**Comment by atodd-geoplan** [comment]
Turns out another leaflet plugin was overriding leaflet Circle causing this issue. I will close.
