### ISSUE TITLE
Consider documenting high accuracy better

### ISSUE THREAD

**Issue by xenotropic** [domoritz/leaflet-locatecontrol#183]
I had to bang my head against the wall for a while to figure out why this was not using full GPS accuracy. I knew it was capable of doing so, because that's what it does on osm.org, but a little frustrating to have to search for how to switch that on.  So, please consider documenting 
`{locateOptions: 'enableHighAccuracy=true'}`  directly in these docs rather than just by reference to leaflet docs. Like maybe in the FAQ you could do "How do I enable high accuracy?"; and/or where you refer to locateOptions, write "this includes enabling high accuracy (i.e., GPS) and tracking the user as they move" or whatever, so that one can find it by searching for "Accuracy" or "GPS" in the docs.  When giving users the option to locate themselves on a map, it is typically to full accuracy, so most devs using this plugin will probably try to find that option. Thanks!

**Comment by domoritz** [comment]
I'm sorry that it was difficult to find the right documentation. I've added some notes. Let me know what you think.

**Comment by xenotropic** [comment]
Looks good, thank you.
