### ISSUE TITLE
leaflet.locatecontrol is not a module

### ISSUE THREAD

**Issue by enocholumide** [domoritz/leaflet-locatecontrol#184]
1. I installed the leaflet.locatecontrol via npm;
2. I tried to import to my component at first and it gave an error of 'cannot find module'
3. Then i installed the types definition, npm install --save @types/leaflet.locatecontrol
4. Now it says leaflet.locatecontrol is not a module 
4. Can you please help me out?

![new picture](https://cloud.githubusercontent.com/assets/24214602/24524597/7c1eb092-1597-11e7-9080-efd4899fad90.png)

**Comment by domoritz** [comment]
Looking at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/leaflet.locatecontrol, I think you want to import `locate` or use `L.control.locate`. I can't really help with your specific setup, sorry.
