### ISSUE TITLE
call back for button creation

### ISSUE THREAD

**Issue by HarelM** [domoritz/leaflet-locatecontrol#185]
Currently I need to manually change the code so that the locate button will look like the rest of the app (I have tooltip which is not just about css).
The code that I write is the following:
```js
onAdd:
...
this._link = L.DomUtil.create('a', 'leaflet-bar-part leaflet-bar-part-single cursor-pointer', container);
this._link.dataset.uibTooltip = '{{resources.showMeWhereIAm}}';
this._link.dataset.tooltipPlacement = "right";
this._link.dataset.tooltipAppendToBody = "true";
this._icon = L.DomUtil.create(this.options.iconElementTag, this.options.icon, this.options.compile(this._link)(this.options.scope)[0]);
```

Is it possible to add a `createButton` to the options and use it when specified?

**Comment by domoritz** [comment]
Sure! Can you send me a PR?

**Comment by HarelM** [comment]
I briefly tested it and it seemed to be working as expected but I believe a few more test should be made.
I was able to override it in my code and present the button with a custom tooltip (which is the main functionality I needed). So I'm quite confident it works as expected.
Let me know if and when you plan to release it so I can get a version with this feature.
Thanks for this awesome plug-in! Keep up the good work!

**Comment by domoritz** [comment]
Done in https://github.com/domoritz/leaflet-locatecontrol/pull/187
