### ISSUE TITLE
Add ability to invoke a callback on "start" and "stop"

### ISSUE THREAD

**Issue by clhenrick** [domoritz/leaflet-locatecontrol#189]
It would be great to be able to pass callbacks for start and stop as options, and to have the control invoke the callbacks when `start` or `stop` are called. For example, if I want my application to toggle a certain UI when the user clicks the locate control. I know Leaflet has a "locationfound" event, but there is no "locationend" event or similar AFAIK.

**Comment by clhenrick** [comment]
Just saw that for altering the behavior of `start` and `stop` the documentation states one can extend the control as [demonstrated here](https://github.com/domoritz/leaflet-locatecontrol#extending). 

If you think start and stop callbacks would be useful though I can submit a PR, otherwise feel free to close.

**Comment by domoritz** [comment]
I think what is there is sufficient. thanks for offering to send a pr!
