### ISSUE TITLE
id's for circle and point geometries

### ISSUE THREAD

**Issue by FelisPimeja** [domoritz/leaflet-locatecontrol#19]
Is it possible to add special id's to theese objects (or make on option to add)? It'll be nice to have a possibility to controll appearence of circle and point through css. For example, through media queries in case of different styles for desktop and mobile devices.

**Comment by domoritz** [comment]
You can pass the cycle style at https://github.com/domoritz/leaflet-locatecontrol/blob/gh-pages/src/L.Control.Locate.js#L7. Also have a look at the possible options at http://leafletjs.com/reference.html#path-options. You can probably add a class yourself but you will have to change the code.

**Comment by FelisPimeja** [comment]
@domoritz The first option is the one I thought about. But it's not that good cause in theory there's a chance of another geometry with such a style to appear on the map  at the same time. Thanks for pointing on the leaflet path-options. I'll try to figure it out though I'm not very good in js. :)

**Comment by domoritz** [comment]
Good luck. Feel free to ask any questions if you get stuck.
