### ISSUE TITLE
L.control.locate() - property locate() does not exist on type 'typeof control'

### ISSUE THREAD

**Issue by MaryCooperGD** [domoritz/leaflet-locatecontrol#191]
Hi, I have installed your plugin using npm and in my js file I have imported:

`import { locatecontrol, locationfound, locate} from 'leaflet.locatecontrol'`

But when writing `L.control.locate()` it gives me the error. Did I miss something?

**Comment by domoritz** [comment]
Since you import the module directly, I think you can't access it on `L`. `L.control.locate` is if you import the module by just including the js file. 

Closing since this is an issue with the particular setup and not the extension.
