### ISSUE TITLE
Plugin is not working in OS X/Chrome

### ISSUE THREAD

**Issue by sanastasiou** [domoritz/leaflet-locatecontrol#192]
OS X Version: : 10.10.5
Chrome: Version 60.0.3112.101 (Official Build) (64-bit)

Symptoms:

The icon keeps spinning but there is no pop up coming up to ask the location access.

In the meantime the same machine has no issues using this:

https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation

So I think there's something wrong with the plugin.

**Comment by domoritz** [comment]
Hmm, it works on my machine. Do you see any errors in the console?

**Comment by sanastasiou** [comment]
@domoritz Thanks for the reply. Yes, I know found out that it also works on my machine too, however compared to my linux machine or my mobile device it is painfully slow ( spinning for like 30seconds ) before I finally get a location. 

Have you experienced something like this in Mac before? I tried enabling/disabling highAccuracy but got similar results.

**Comment by domoritz** [comment]
Hmm, I haven't had problems like that before. I'm surprised that the problem only occurs with my plugin as I am just calling the browser's location API.

**Comment by domoritz** [comment]
This doesn't seem to be a problem with the plugin.
