### ISSUE TITLE
Extend the createButtonCallback to work properly with iconLoading

### ISSUE THREAD

**Issue by astalegale** [domoritz/leaflet-locatecontrol#194]
Hi,  thanks for this very useful plugin!

I've create a custom createButtonCallback for using with materialize icons set.
There is a difference between using font awesome & materialize:
font awesome render: <span class="fa fa-icon"></span>
materialize render: <span class="">materialize_icon_code</span>

so when the _setClasses function doesn't work properly, i'll suggest to create a callback to manage it.

Regards
Alex

**Comment by domoritz** [comment]
Sounds useful. Do you want to send a PR?

**Comment by Dr-Mx** [comment]
This method may also be useful for when you implement Font Awesome 5

**Comment by domoritz** [comment]
> This method may also be useful for when you implement Font Awesome 5

Can you explain?
