### ISSUE TITLE
Issue with centering location box.

### ISSUE THREAD

**Issue by mdeetz90** [domoritz/leaflet-locatecontrol#195]
Kind of an odd error and I'm a beginner so bear with me please. In the demos and photos the arrow to click on centering your location is centered and fits nicely with the zoom in and out buttons. Mine however is offset and the box is larger than it should be with the blue marker slightly off to the right. Making it look odd, is there a way to fix this? Like I said I'm a beginner and it could be obvious, thanks in advance.

**Comment by domoritz** [comment]
Did you include the css file? Can you send a screenshot of what it looks like for you?

**Comment by mdeetz90** [comment]
![offset](https://user-images.githubusercontent.com/31522915/29948645-05201520-8e7e-11e7-963d-9d61dd310232.PNG)

Yes I included the css file as instructed, here is a pic of what I'm talking about probably makes it easier to explain.

**Comment by domoritz** [comment]
Odd. Could you send me a link to an online version of this so that I can debug? Off the top of my head, I can't see what the issue is.

**Comment by mdeetz90** [comment]
Yeah I can try, I am just running it off of my pc now. I quickly loaded it onto a test server I use though. It probably won't work correctly but the error is still there. Lmk if you need something different. Thanks again.

http://mattstesthosting-com.stackstaging.com/map.html

**Comment by lucawen** [comment]
How you resolve this ?? I have the same problem.. Running on ionic 3 and angular 6.

**Comment by lucawen** [comment]
I fix this using a trick:

`.leaflet-control-locate > a > span {
        margin-left: -8px;
        margin-top: -8px;
    }`
