### ISSUE TITLE
L.Control.Locate is undefined after bundle with r.js

### ISSUE THREAD

**Issue by sookoll** [domoritz/leaflet-locatecontrol#196]
Without bundling it works just fine, after optimizing L.Control.Locate is undefined.
My conf:
```
requirejs.config({
  "paths" : {
    "leaflet" : "lib/leaflet",
    "leaflet.locate": "lib/L.Control.Locate",
    ...
  },
  "shim": {
    "leaflet.locate": {
       deps: ['leaflet']
    }
  }
})

```
Current solution that works for me, was:
```
L.control.locate = function (options) {
  //return new L.Control.Locate(options);
  return new LocateControl(options);
};
```

**Comment by domoritz** [comment]
Thanks for the issue report. What is r.js? isn't this an issue with the bundler and not this plugin? Is there something I can do to prevent this?

**Comment by sookoll** [comment]
r.js is optimization script for RequireJS module loader. I'm not entirely sure, but it seems, that optimization remove module loaders definitions from files, so L.Control.Locate will never declared, so here: https://github.com/domoritz/leaflet-locatecontrol/blob/gh-pages/src/L.Control.Locate.js#L587 it is undefined and throw error.
One solution is to replace `return new L.Control.Locate(options);` with `return new LocateControl(options);`
I can create pull request for that if anybody smarter confirm, that it is correct fix for that.

**Comment by KeepSummerSaf3** [comment]
Was a solution reached for this issue? It would seem as if locate is intended to be an extension of L.control; however, as sookoll mentioned it is not defined.
