### ISSUE TITLE
Interpretation of location accuracy

### ISSUE THREAD

**Issue by TomazicM** [domoritz/leaflet-locatecontrol#197]
Hi!

Example on "official" Leaflet page http://leafletjs.com/examples/mobile/ draws accuracy circle with radius that is equal to accuracy given by Leaflet map.locate method divided by 2. Leaflet-locatecontrol extansion draws accuracy circle with original accuracy radius.

Which interpretation of accuracy is right?
 - Mitja

**Comment by Berkmann18** [comment]
Both seems to not be accurate enough to tell.

**Comment by domoritz** [comment]
I couldn't find the definition of accuracy but at some point, I compared my implementation to google maps and it matched. If you have more input, please share it.

**Comment by Berkmann18** [comment]
@domoritz Does the plugin accurately find you?
Even with `enableHighAccuracy: true` options and making sure I can be geolocated, it (just like Leaflet's native locate method) fail to be more than 10m accurate which is terribly annoying.

**Comment by domoritz** [comment]
@Berkmann18 That's an issue with the browser. I don't think there is anything I can do.

**Comment by Berkmann18** [comment]
@domoritz It seems like you're right. Hopefully it would work for other people using the app I'm making.
