### ISSUE TITLE
plugin produces magnifying glass-ish zoom behaviour 

### ISSUE THREAD

**Issue by gawgeo** [domoritz/leaflet-locatecontrol#201]
Hello there,
I'm using your plugin to locate the user on click on a personal mapping project. Using chrome (mobile) on an Android smartphone, the plugIn seems to produce a magnifying glass-ish zoom behaviour. However, using the same device and openig the demo webpage, there is no such behavior. How can I deactivate this?
thanks a lot!

![2017-11-16 12 33 09](https://user-images.githubusercontent.com/33719943/32889410-2ec88824-cacb-11e7-88f4-8b1c5d547fa9.jpg)

**Comment by domoritz** [comment]
That's an issue with how chrome on android helps you see small inks. I don't know how Chrome decides to do it.
