### ISSUE TITLE
issue with HTTPS

### ISSUE THREAD

**Issue by kronick07** [domoritz/leaflet-locatecontrol#202]
Trying to add geolocate to store locator map. Getting a Mixed Context trying to load over HTTPS but it is pulling this data from insecure script. Even though in my code I have it as HTTPS. What is going on here? 
![snip](https://user-images.githubusercontent.com/34194048/33681305-201542a0-da92-11e7-848c-6c3e55a9bbb6.PNG)

**Comment by domoritz** [comment]
Somewhere in there, your code is requesting the locate control files via http. I recommend that you use npm or a proper CDN. 

I'm going to update the readme to make this clearer.
