### ISSUE TITLE
custom parent div possible?

### ISSUE THREAD

**Issue by Revo86** [domoritz/leaflet-locatecontrol#205]
Is it possible to place the button in a custom div instead of e.g. leaflet-top ? I tried declaring the div class name or id in position, but that didn't work. I really wanna avoid custom css placing or a programming approach. thanks!

**Comment by domoritz** [comment]
I haven't needed this feature yet but I could be happy to accept a pull request.

**Comment by pixels-for-breakfast** [comment]
@Revo86 Any news or progress on this? Were you able to move the locate-control outside the map-area?

**Comment by domoritz** [comment]
I don't have the cycles to do this, no.

**Comment by mvl22** [comment]
To have an external button, I have got this workaround to work:

HTML - create an image with a link:

```
<!-- Custom geolocation button -->
<div class="geolocate-button">
    <a href="#"><img src="mybutton.png" /></a>
</div>
```

CSS - hide the default button created by the plugin:

```
/* Hide default locate button */
.leaflet-control-locate {display: none;}
```

Javascript (jQuery) - simulate click of (now-hidden) standard button if the custom button is clicked:

```
// Support custom geolocation button - pass on click to (hidden) default button
$(function() {
    if ($('div.geolocate-button').length) { // Custom button support
        $('.geolocate-button a').click( function(e) {
            $('.fa-location-arrow').click();    // Simulate click of icon
            e.preventDefault();
        });
    }
});
```
