### ISSUE TITLE
'L' is not defined when importing from custom folder

### ISSUE THREAD

**Issue by ghost** [domoritz/leaflet-locatecontrol#206]
I installed your plugin via npm, copied the folder in node_modules to another destination, and tried to import from that new destination (because I needed to make change in your code), instead of node_modules.
But after I did this, I get these errors:

 

>  12:41  error    'define' is not defined                                   no-undef
>    13:9   error    'define' is not defined                                   no-undef
>    18:38  error    'L' is not defined                                        no-undef
>    26:43  error    'L' is not defined                                        no-undef

This is how I imported your code:
```
import "./localPlugins/leaflet.locatecontrol/src/L.Control.Locate.js"
import "./localPlugins/leaflet.locatecontrol/dist/L.Control.Locate.min.css"


```
Interesting to note is that when I imported your plugin from node_modules everything worked fine (except an error - https://github.com/domoritz/leaflet-locatecontrol/issues/182-  for which I had to modify the code), but when I copied that same code to a different folder and tried to import it I get the error as above.

**Comment by domoritz** [comment]
Are you using webpack? I don't know how you are using the import here.

**Comment by ghost** [comment]
@domoritz I think I fixed it. e.g. inside file L.Control.Locate.js

I changed 
`            module.exports = factory(L);`
to
`            module.exports = factory(window.L);
`

e.g. appended window to places where the error was.

though I am not sure why this fixed this issue, I used an advice.
