### ISSUE TITLE
Ability to set a location for the user

### ISSUE THREAD

**Issue by jszwedko** [domoritz/leaflet-locatecontrol#209]
Add the ability to programmatically set the current location of the locatecontrol.

We have a use case where we'd like to:

* Locate the user on a splash page
* Once located, load the map with the initial location of the user to have it rendered as the locatecontrol renders it
* Let the user thereafter use the locate control to pan the map back to their current (or new) location

Right now we are working around this by loading the map and immediately calling `.start()` on the control, but find this to be slightly confusing for users who expect the map to be loaded with their current location already displayed.

I can take a shot at this, but wanted to get feedback on whether this feature would be desirable before spending too much time on it.

Thanks for this great library!

**Comment by domoritz** [comment]
Thanks for creating the issue. This sounds like a very special case and I don't think I'd want that in the main library. However, if there is a way you can think of adding a plugin API, I'm happy to consider a PR. I'm going to close this issue as it's not actionable right now but feel free to respond.

**Comment by jszwedko** [comment]
:+1: thanks for engaging in the discussion. I agree it likely isn't a common use case, but figured I'd ask.

We essentially want to do something similar to Yelp.

**Comment by domoritz** [comment]
Thanks for understanding.
