### ISSUE TITLE
Tag?

### ISSUE THREAD

**Issue by tmcw** [domoritz/leaflet-locatecontrol#21]
We're looking at using this for OpenStreetMap, any chance you can tag the current state to have something stable to hang on to?

**Comment by domoritz** [comment]
@tmcw I'd be happy to add tags. Do you prefer a tag `v1` that moves when things are added or fixed as long as the API does not change or semantic [versioning](http://semver.org/)?

**Comment by tmcw** [comment]
something like `v0.0.0` or `v1.0.0` (depending on whether you want to increment the main on tweaks) would be great.

**Comment by domoritz** [comment]
For the 42th commit, here is the first tag: https://github.com/domoritz/leaflet-locatecontrol/tree/v0.9.0.

Since this is not a 1.0 yet, the API might change even in minor versions.
