### ISSUE TITLE
Demo doesnt work

### ISSUE THREAD

**Issue by ghost** [domoritz/leaflet-locatecontrol#211]
The demo doesn't find my location, what can be the reason?

**Comment by domoritz** [comment]
That's probably a problem with your browser as it works for me. 

What browser do you use and does the normal location API work? Any errors in the js console?

**Comment by ghost** [comment]
I use Firefox 61.0.2, there is no error in console :/

**Comment by domoritz** [comment]
Try https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API#Live_Result

**Comment by ghost** [comment]
Hmm, "Geolocation is not supported by your browser". Thanks for the link. Do you know the percentage of those users who use geolocation in browser?

**Comment by domoritz** [comment]
I'm not sure why but then the issue is not this plugin.
