### ISSUE TITLE
change default follow?

### ISSUE THREAD

**Issue by jayenashar** [domoritz/leaflet-locatecontrol#213]
currently it is `'untilPan'` but i like `'untilPanOrZoom'`

please use comments to discuss.

**Comment by domoritz** [comment]
I think I have a good argument. When you zoom, you don't zoom to the user's location but the cursor. So with some zooming you can move the user's location out of the view. 

Let's change the default and bump the version.

**Comment by jayenashar** [comment]
sorry for my poor communication!  that's what i was trying to say when i describe how i pan by zooming.

**Comment by domoritz** [comment]
Sorry for being slow at getting it. New version has been released.
