### ISSUE TITLE
Combined location and direction / compass feature

### ISSUE THREAD

**Issue by brendanheywood** [domoritz/leaflet-locatecontrol#214]
There are other leaflet plugins that add a compass control to the map eg

https://github.com/stefanocudini/leaflet-compass/blob/master/src/leaflet-compass.js

![image](https://user-images.githubusercontent.com/187449/47948440-73213280-df85-11e8-8df0-26beb6ad2c93.png)

But to me it makes more sense UX wise to have the option to combine this with this location control. If this api is available then it's turned at the same time as the gps and updates while ever the gps updates. If it isn't available the gps location appears as it currently does, but where it does appear there would be an extra 3rd marker overlaid over the markerClass with options like compassClass and compassStyle. This would probably need to be inside a proxy marker which handles the rotation automatically.

The default styles I think would be similar to the apple maps, with a little blue arrow

![image](https://user-images.githubusercontent.com/187449/47948462-d0b57f00-df85-11e8-9c88-40ac1e51145f.png)

**Comment by domoritz** [comment]
I like the idea and would be happy to review a pull request.

**Comment by brendanheywood** [comment]
Awesome, would you be open to bundling some minor style changes to the base blue marker style so it works better when the compass arrow is present? The white ring around the marker appears to be the de facto style in all the major map apps and without that contrast the little blue arrow would be hard to see.

**Comment by domoritz** [comment]
Yes, I'm open to that if it looks good and can be styled easily.

**Comment by brendanheywood** [comment]
@domoritz sorry I didn't send this last night: I have a functional wip, but I'm not quite happy with it yet. The main sticking point is the use of a L.Circle for the blue dot instead of a marker which means there is a zoom artifact where it scales with the map and then has to redraw on zoomend. I've currently added the arrow as a path alongside it but I don't like it and think this would be much better if they were both markers, not paths, so they are perfectly synchronized and neither should need a re-draw after a zoom (and so also work nicely with fractional zoom and while you are pinch zooming etc).

So I'm planning to move both of these to new classes which use the divIcon marker, and some glue code so that they accept setStyle and are backward compatible with L.Circle. It's just a little bit more of a change than expected so wanted to make you are broadly ok with that direction. I don't want to pull in any other dependencies.

**Comment by domoritz** [comment]
That sounds great! I'm also okay with breaking backward compatibility in rare cases where it is reasonable. Thank you for taking the lead on this.

**Comment by domoritz** [comment]
Done and released. Thank you!

**Comment by brendanheywood** [comment]
Thanks for the prompt review and merge :+1:
