### ISSUE TITLE
A method or process to stop tracking but keep the gps active

### ISSUE THREAD

**Issue by brendanheywood** [domoritz/leaflet-locatecontrol#216]
This may be either code methods or maybe just an update to the docs. The use case is:

1) the map setView is either untilPan or untilPanOrView
2) the user has clicked the locate button is now tracking, icon is orange. Lets say they are in a car and moving fast
3) lets say they interact with the map, like they click a popup which opens in the center of the map. They are reading the popup. But they haven't panned or zoomed so the tracking is still active and the map keeps moving and the popup scrolls offscreen while they are reading it.

In this case I would want the location to remain active, the location would keep updating, but the following would be suspended, possibly temporarily.

I can see a couple potential solutions to address this directly or indirectly:

a) add more methods besides start() and stop() with something in the middle, perhaps something like stopFollowing() startFollowing() which is effectively like a zero-pan or zero-zoom but keeps the gps active.

```
on('popupopen', function(e) {
  lc.stopFollowing();
})

on('popupclose', function(e) {
  lc.startFollowing();
})
```

b) perhaps a more flexible approach (but possibly not as simple to explain) is that the start() method has an optional string argument which is the same as a setView string. This means you could set the control into a certain state independent of the state that clicking the control would put it into. So we would have the option.setView which is the state that the control is put into when the button is clicked, and we would also have an independant this._setView state which can be set directly.

This opens up lots of possibility such as:

The use case above, I want to keep active but stop following:

```
on('popupopen', function(e) {
  lc.start(false);
})
```

Another one I'd really like is on page load I want to get immediately be active and draw the location which may be outside the viewport, but not update the position and follow until I click the locate button. This could be done with:

```
lc = L.control.locate({
    setView: "untilPanOrZoom"
}).addTo(map);
lc.start(false);
```

I think I could probably get this behavior by watching a bunch of events and just changing the setView option but this seems brittle and prone to leaving it in the wrong state.

c) It would also be useful if the control fired some events so we can watch when we start or stop following,

```
this.fire('locationfollowstart', data);
this.fire('locationfollowend', data);
```

**Comment by domoritz** [comment]
`lc.stopFollowing()` could just set `_userPanned`, I think. I'm open to adding the two functions you mentioned. a) and c) make sense to me. b) seems confusing to users.
