### ISSUE TITLE
Add clickBehavorior for inViewNotFollowing

### ISSUE THREAD

**Issue by brendanheywood** [domoritz/leaflet-locatecontrol#217]
Use case:

1) the map setView is untilPan*
2) I start tracking, icon is orange
3) I stop to look at something, icon is blue
4) I click the icon again to resume tracking (expected behavior in every major map app), but instead of resuming the tracking it turns the location off completely. If I tap again then does what I want.

Suggested solution:

```
    clickBehavior: {
        inView: 'stop',
        inViewNotFollowing: 'setView',
        outOfView: 'setView',
   },
```

This would only take affect if you are both inView, and not following, AND the setView option is either 'always' or 'untilPan*'. I would suggest this as both a new option as well as being the default value so it aligns with other maps.

**Comment by domoritz** [comment]
The current behavior toggles locating and not locating except if the user is outside the visible bounds. I think that's a reasonable default. So, while I think the default should stay for now, I am happy to add options to get the behavior you describe.
