### ISSUE TITLE
setView: "untilPan" + zoom gets reset on next location event update

### ISSUE THREAD

**Issue by brendanheywood** [domoritz/leaflet-locatecontrol#224]
If setView: 'untilPan', then you can zoom in or out (either using the buttons, or the +/- keys, or the mouse wheel) and the location stays centered as expected.

But then after some indeterminate time the next locate update event happens and the zoom level gets reset. I'm not sure if this is a bug or a feature but if I've zoomed then I'd expect it to stay zoomed at the same level but still continue tracking, ie how google maps works.

**Comment by domoritz** [comment]
This is the current behavior. I don't think it's the optimal behavior but it's also not a bug. Changing it would introduce some hidden state (user has zoomed but not panned) and that's not good. Similar to #225, should we change the default?

**Comment by brendanheywood** [comment]
Maybe it could be a new keepCurrentZoomLevel option value, something like:

```
keepCurrentZoomLevel: false  // never
keepCurrentZoomLevel: true  // always
keepCurrentZoomLevel: 'untilZoom'  // Only applies if setView == always or untilPan
```
