### ISSUE TITLE
Smooth interpolation / prediction of sparse locations

### ISSUE THREAD

**Issue by brendanheywood** [domoritz/leaflet-locatecontrol#227]
I did a bunch if field testing today at car speeds and broadly at high speeds the locations updates are really jumpy. There is 2 overlapping root causes:

1) there is no smooth animation to reflect the velocity of the device, between sparse locationFound events. Note this not as simple as just animating to the new location as this will add noticeable lag. 

Instead this needs to actually be predictive and animate ahead in time to a predicted position. There are various contenders for how to go about this, most of the literature talks about Kalman filters

https://en.wikipedia.org/wiki/Kalman_filter#Example_application

The specific use case for 2 dimensions + velocity is only a few lines of code, eg

https://stackoverflow.com/questions/1134579/smooth-gps-data

The bit that I'm not sure about us where this code should live, ie should it live in leaflet core and it should send a continuous stream of fake locationFound update events (if desired) and this control just uses it. This would make more sense if there are other controls also hanging off the same events so they are synchronized. But I'd bet that almost everyone just wants this control for locations and very little else so it could be bundled in here.

Or maybe some code in the middle which consumes leaflet core locationFound events and emits a more continuous stream of normalized smoothed smoothedLocationFound events, and this control can just have a options to listen to a different set of events.

2) at high speeds, almost regardless of location accuracy, the map is zoomed in too far and you may have to reload several new tiles every second and the network can't keep up. It's also just a blur that you can't usefully track. This is fairly easily worked around now that we have the getLocationBounds option, but I think this is worth actually changing the default implementation to expand the bounds linearly based on velocity, eg tune it so that regardless of your speed you will never pan more than 1 viewport every X seconds. At low speeds this would have no effect.

Development for this will be a pain as I cannot find any browser plugins which can simulate a moving location over time. This is the closest I could find:

https://stackoverflow.com/questions/27999510/emulating-geo-location-in-chrome-with-moving

I have to test more to see how reliable the heading and speed attributes are of the location event and whether these can be used directly or whether they need to be inferred.

**Comment by domoritz** [comment]
I think this functionality is useful in its own right and could be a leaflet plugin that sends fake location events. Once installed, it would just work with this extension.

**Comment by 8volution23** [comment]
I found this plugin to smoothly move a marker on Leaflet:
https://gitlab.com/IvanSanchez/Leaflet.Marker.SlideTo
Is there any way I could use it with locatecontrol? Thanks!

**Comment by domoritz** [comment]
Smooth movements are not enough. The problem is that you would always lag behind. At least I would personally prefer to have the up to date location instead of smooth movements.

**Comment by 8volution23** [comment]
Thanks for your answer. For the application I am working on, some lag is preferable to jumpy movements. I accesed the user marker via lc._marker and tried to pass it to the SlideTo plugin but did not work.

Also, I have noticed that the compass bearing is not working on Android Firefox 65. Works fine on Chrome though.
