### ISSUE TITLE
onLocationOutsideMapBounds doesn't work

### ISSUE THREAD

**Issue by 2803media** [domoritz/leaflet-locatecontrol#228]
Hi

I use that in order to prevent locate outside the map:

```
L.control.locate({
    onLocationOutsideMapBounds: function(control) {
                control.stop();
                alert(control.options.strings.outsideMapBoundsMsg);
            },
}).addTo(map);
```

But when I click on the marker it locate me and drag me to the point even if it's outside the current map. 

Any idea?

Leaflet 1.3.1
Last locatecontrol version

Thanks

**Comment by domoritz** [comment]
Where do you set the map bounds?

**Comment by 2803media** [comment]
Humm maybe it's for that it doesn't work ;)

Shoud I use that to get the bounds?

```
getLocationBounds: function (locationEvent) {
                return locationEvent.bounds;
            },
```

Or do I must use 

```map.getBounds();```

**Comment by domoritz** [comment]
I expect you to use https://leafletjs.com/reference-1.3.4.html#map-maxbounds. I don't know the leaflet API enough to answer your specific question. I'm closing this issue since everything works as expected.

**Comment by 2803media** [comment]
Usually I use the map.getBounds(); to get the bounds of the maps but I don't understand how you pass bounds values to onLocationOutsideMapBounds

**Comment by domoritz** [comment]
You can look at the code. I hope that clarifies how it works.

**Comment by 2803media** [comment]
I already look at it but sorry I'm not a high level dev so example is the best way for me to understand... Sorry to be a noob to understand how the callback works ;)

**Comment by 2803media** [comment]
Finally I understand the logic, it was not trivial! So you need to but maxBounds to the map so that if the user is outside you display the alert message. 

I put the code if someone need it

```
var map = new L.Map('map', {
    layers: [mapbox],
    center: [51.505, -0.09],
    zoom: 10,
    zoomControl: true,
    maxBounds: [
        //south west
        [51.28940590271679, -0.9681701660156251],
        //north east
        [51.72022261695932, 0.7882690429687501]
        ],
});

L.control.locate({
    strings: {
        title: "Localisez moi!",
        popup:"Vous êtes à {distance} {unit} de ce point",
        outsideMapBoundsMsg:"Vous semblez être en dehors de la carte, merci de dézoomer un peu",
        metersUnit:"mètres",
    },
    onLocationOutsideMapBounds: function(control) {
        control.stop();
        alert(control.options.strings.outsideMapBoundsMsg);
    },
    icon: "fa fa fa-crosshairs",
}).addTo(map);
```

**Comment by domoritz** [comment]
Thank you @2803media for digging into the code!
