### ISSUE TITLE
How to get current location if it has already been found?

### ISSUE THREAD

**Issue by tstibbs** [domoritz/leaflet-locatecontrol#229]
I can't find how to get the current location, if it has already been found.

I.e. if the user has clicked on the control to get their location, then later on another piece of code wants to get the location, it has no way to find the existing location. Listening to the `locationfound` event doesn't help because that has already fired, and won't fire again unless the location changes (I think). Calling `start()` again doesn't do anything, because it's already got the current location.

So is there a way to get the location? Looks like it's currently stored in `control._event.latlng` but doesn't feel right digging in to the internal state.

**Comment by tstibbs** [comment]
One workaround appears to be to listen for `locationfound` and then call `lc.stop(); lc.start();` - this seems to force it to fetch the location again and will then fire the event, even if the location hasn't actually changed, but I'm not sure if there any edge cases or side effects to watch out for.

**Comment by drqwerty** [comment]
For those who have this problem with Ionic Capacitor.

I've used code like this, getting the user's current location through Capacitor before calling `start ()`, and I've managed to significantly reduce the time to find the user's location when accessing the map a second time.

```typescript
Plugins.Geolocation.getCurrentPosition();
this.lc.start();
```
