### ISSUE TITLE
locate then center map to user location without zooming

### ISSUE THREAD

**Issue by gamecubate** [domoritz/leaflet-locatecontrol#23]
Is there a way to center the map on user's location without zooming?

**Comment by domoritz** [comment]
We would probably need an option to change [this line](https://github.com/domoritz/leaflet-locatecontrol/blob/gh-pages/src/L.Control.Locate.js#L111) to something like `setView` and remember the current zoom level. Would you like to write this and send a pull request? You would probably want to call the option `justMove` and add it to the readme as well.

**Comment by gamecubate** [comment]
Okay thanks. I'll take a look at it and see what I can come up with.

**Comment by domoritz** [comment]
@gamecubate Code contribution is very welcome. I'll close this issue for now and hope to see a pull request. If you have any questions or problems, I'm happy to help.
