### ISSUE TITLE
How to get coordinates on popup after location has been found?

### ISSUE THREAD

**Issue by kurtvon** [domoritz/leaflet-locatecontrol#231]
Once I locate my position on the map, I would like to be able to click the blue icon and have the popup that says "you are within x meters from the location" to say the lat and long instead.

How can I achieve this?

**Comment by domoritz** [comment]
You could try to override the method to create the popup. 

I reserve the GitHub issues for bugs and feature requests.

**Comment by PedroVenancio** [comment]
Hi @domoritz 

This can easily be added to https://github.com/domoritz/leaflet-locatecontrol/blob/gh-pages/src/L.Control.Locate.js

```
            var coordinatesLat = this._event.latlng.lat;//.toFixed(5);
            var coordinatesLng = this._event.latlng.lng;
```
(...)
```
            var t = this.options.strings.popup;
            function getPopupText() {
                if (typeof t === 'string') {
                    return L.Util.template(t, {distance: distance, unit: unit, coordinatesLat: coordinatesLat, coordinatesLng: coordinatesLng});
                } else if (typeof t === 'function') {
                    return t({distance: distance, unit: unit, coordinatesLat: coordinatesLat, coordinatesLng: coordinatesLng});
                } else {
                    return t;
                }
            }
```

And then the popup filled with

`popup: "Lat:  {coordinatesLat}<br>Lon:  {coordinatesLng}<br>Error: {distance} {unit}"`

Can be a good enhancement for the popup.

Thank you very much for this great plugin!
