### ISSUE TITLE
setView: false not working

### ISSUE THREAD

**Issue by nodu** [domoritz/leaflet-locatecontrol#24]
I assume when setView: false is set, the map should not change zoom, or set focus to the location.  It should just show the blue dot for location, correct?  If I'm right in assuming this, it seems setView: false is broken as it zooms right into the marker's positon (well actually it zooms into another location and when clicked again, zooms to the correct location.)

**Comment by domoritz** [comment]
I think I messed up this line: https://github.com/domoritz/leaflet-locatecontrol/blob/gh-pages/src/L.Control.Locate.js#L53.

**Comment by domoritz** [comment]
@DearHunter can you confirm that this error is now fixed?

**Comment by nodu** [comment]
Beautiful! Fixed. Thank you for your hard work
