### ISSUE TITLE
Can't set bubblingMouseEvents to true;

### ISSUE THREAD

**Issue by hjrobinson** [domoritz/leaflet-locatecontrol#240]
I can't set bubblingMouseEvents to true for the marker.  It doesn't work in the marker style options.

**Comment by domoritz** [comment]
Can you try to find out what the problem is? I have never used that functionality and would like to know what's preventing it from working.

**Comment by hjrobinson** [comment]
After further review it seems to be a peculiarity in my code that conflicts with the plugin. After a location is found my particular onclick event won't propagate to the map. I can't produce a minimal example because my code is too verbose.  A simple click event that fired an alert seemed to work fine after finding a location.  I resolved to use the built in locate function (https://leafletjs.com/examples/mobile/) which works but I would prefer to use your plugin because it seems to redraw the tiles more quickly upon finding a location.  If you have anything to add let me know otherwise I'll close the issue unless I'm able to identify the specific problem.

**Comment by hjrobinson** [comment]
Closing.
