### ISSUE TITLE
Not work with fullHash plugin

### ISSUE THREAD

**Issue by nemethtamas** [domoritz/leaflet-locatecontrol#241]
With fullHash plugin (https://github.com/KoGor/leaflet-fullHash) not draw marker, and  accuracy circle. Flyto function work.

**Comment by domoritz** [comment]
Did you file an issue with full hash or do you know what's causing the problem?

**Comment by nemethtamas** [comment]
Example:
https://heyjoe.hu/test/hash_geoloc/

Hash work, geolocation work.

https://heyjoe.hu/test/hash_geoloc/#8/47.005/16.820/mapbox

Hash work, gelocation find me, but it doesn't draw marker, and circle.

**Comment by domoritz** [comment]
I get an `ERR_CONNECTION_TIMED_OUT` for the first page. Unfortunately, I don't have the cycles to look into this. Please debug this issue find a more specific problem with my library.

**Comment by Phyks** [comment]
I was having a related issue. When using `leaflet-fullHash` and `leaflet-locatecontrol` together, the active layer is no longer set correctly from the hash.

This is coming from https://github.com/domoritz/leaflet-locatecontrol/blob/gh-pages/src/L.Control.Locate.js#L338. I commented this line out and now I have fullHash + locatecontrol working nice, except for the marker not drawn (which is expected, the layer is no longer added to the map). This behavior is fine with me, although not perfect.

**Comment by domoritz** [comment]
I'll leave this issue open until we have a fix for the underlying issue. If someone can send a PR, that would be awesome.

**Comment by adriankwiat** [comment]
I found solution for this - you must open layer some time after loading page (e.g. 500 ms):
```js
setTimeout(function() {
  locateControl._layer.addTo(map);
}, 500);
```
