### ISSUE TITLE
Current location marker not displaying

### ISSUE THREAD

**Issue by jamesinealing** [domoritz/leaflet-locatecontrol#243]
Hi, I have implemented locatecontrol on https://astreetnearyou.org. I'm using https://cdnjs.cloudflare.com/ajax/libs/leaflet-locatecontrol/0.67.0/L.Control.Locate.min.js

My config is 

    // locate control
    L.control.locate(
      {
        flyTo: true,
        strings: {title: "Zoom to current location"},
        icon: "fa fa-map-pin",
        locateOptions: {maxZoom: 16}
      }
    ).addTo(bootleaf.map);

The control appears and works, but the location marker/circle is not appearing.  I'm not sure how I can debug this in terms of seeing if it has added the marker but it is not visible, or if there is a clash with some other code, so any help would be much appreciated. Thanks

**Comment by domoritz** [comment]
That's odd. The [demo](https://github.com/domoritz/leaflet-locatecontrol/blob/gh-pages/demo/script.js) uses a similar script. Maybe you are adding another layer afterward? Make sure that you add the locate layer last.

**Comment by lymine1996** [comment]
I'm facing the same issue right now. The control did work and zoom the map to where I was but the location marker just couldn't show up., either using Chrome or Firefox. Any solution to this?

**Comment by peterjcole** [comment]
> That's odd. The [demo](https://github.com/domoritz/leaflet-locatecontrol/blob/gh-pages/demo/script.js) uses a similar script. Maybe you are adding another layer afterward? Make sure that you add the locate layer last.

Thanks for this, I was having the same issue on an app which dynamically adds layers, as I didn't realise the locate layer needed to be added last. I fixed this by providing a LayerGroup into the config object:
```js
      const locateLayer = new L.LayerGroup()

      L.control.locate({
        layer:locateLayer
      }).addTo(map)
```
Whenever adding a new unrelated layer to the map, I first call `locateLayer.remove()`, then add my layer, then `locateLayer.addTo(map)`.

Can I suggest considering mentioning this in the docs? It's not super intuitive for an app which dynamically adds layers later on. I would raise a PR to do it, but I don't have the full context on when this is and isn't required. Thanks!
