### ISSUE TITLE
net::ERR_ABORTED 404 and L.control.locate is not a function

### ISSUE THREAD

**Issue by Yao-C** [domoritz/leaflet-locatecontrol#250]
Hei, I tried the setting as you described in https://codepen.io/Yao-C/pen/xxKXJMq, but get the error as following, can you check what is the problem. Besides, I also tried to copy L.Control.Locate.css and js to file (demo is: https://codepen.io/Yao-C/pen/OJLgrvX?editors=1010) , but still get error L.control.locate is not a function. 

xxKXJMq:26
GET https://cdn.jsdelivr.net/npm/leaflet.locatecontrol@[VERSION]/dist/L.Control.Locate.min.css net::ERR_ABORTED 404

xxKXJMq:44 
GET https://cdn.jsdelivr.net/npm/leaflet.locatecontrol@[VERSION]/dist/L.Control.Locate.min.js net::ERR_ABORTED 404

pen.js:28 
Uncaught TypeError: L.control.locate is not a function
    at pen.js:28

**Comment by domoritz** [comment]
Replace [version] with the version number.
