### ISSUE TITLE
Marker icon is not showing

### ISSUE THREAD

**Issue by Krukarius** [domoritz/leaflet-locatecontrol#251]
I have a blank rectangle unlike to example provided, where the search icon is clearly shown.
Any ideas how to fix it?

I tried sth like this:
icon: "location.png",

but in vain

**Comment by domoritz** [comment]
Are you including font awesome? Does the example in this repo work?

**Comment by Krukarius** [comment]
Yes I already included fonts awesome and it works now. Thanks for hint. Rgds.
