### ISSUE TITLE
Disable marker animation

### ISSUE THREAD

**Issue by adriankwiat** [domoritz/leaflet-locatecontrol#256]
Is possible to disable marker animation?

Instead of this:
![4](https://user-images.githubusercontent.com/36125672/68427326-30062a80-01aa-11ea-948f-11da01e6aa21.gif)

I want this:
![5](https://user-images.githubusercontent.com/36125672/68427325-30062a80-01aa-11ea-86b4-523fb4956e69.gif)

**Comment by domoritz** [comment]
Yes, change the CSS. The default adds CSS adds the animation: https://github.com/domoritz/leaflet-locatecontrol/blob/gh-pages/src/L.Control.Locate.scss#L22.
