### ISSUE TITLE
Possible to get current location after every 10 seconds.

### ISSUE THREAD

**Issue by sakjain02** [domoritz/leaflet-locatecontrol#257]
Possible to get current location after every 10 seconds of no interaction with L.Control.Locate method?
I have tried it but it keeps on adding button which I don't want.

**Comment by skn-hyn** [comment]
Got the same thing.

**Comment by skn-hyn** [comment]
@sakjain02 Got the same thing. Did you solve it ?

**Comment by domoritz** [comment]
I’m just calling the leaflet api so this is a question for leaflet and the browser apis.
