### ISSUE TITLE
iPhone raises "Geolocation error: User denied Geolocation"

### ISSUE THREAD

**Issue by domoritz** [domoritz/leaflet-locatecontrol#260]
Accessing https://www.domoritz.de/leaflet-locatecontrol/demo/ on an iPhone causes "Geolocation error: User denied Geolocation" and the location request does not work.

**Comment by domoritz** [comment]
Ahh, it works when you allow location access in the settings: https://www.badgermapping.com/knowledgebase/turn-geolocation-iphone/

**Comment by wanglin88207056** [comment]
my chorme has the same problem,buy ie and firefox is useful
