### ISSUE TITLE
Multiple permission dialogs in iOS 13 when using showCompass 

### ISSUE THREAD

**Issue by sveine** [domoritz/leaflet-locatecontrol#261]
I am getting two dialogs:
- The website «x» would like to use your current location
- «x» Would like to Access Motion and Orientation

Is it possible to only display one dialog?

**Comment by domoritz** [comment]
Good question. We request orientation in https://github.com/domoritz/leaflet-locatecontrol/blob/gh-pages/src/L.Control.Locate.js#L476 and location requests are handled by leaflet. I don't know whether we can easily combine the requests. If you can figure out a way to request both permissions through the browser, we could try to use it here as well. This is not an issue specific for this control

**Comment by sveine** [comment]
I think I found that it's not possible now. In the future the solution could be to use the Permissions API https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API

**Comment by domoritz** [comment]
Thanks for the link. So we could do a `Permissions.requestAll` (if supported, which it isn't in Safari) at the beginning to only show a single dialog.
