### ISSUE TITLE
Doesn't work on Chromium

### ISSUE THREAD

**Issue by smartm0use** [domoritz/leaflet-locatecontrol#265]
Hello,
did you know that Locate doesn't work on Chromium browser?

I'm using Chromium version 80.0.3987.163, running on Ubuntu 18.04 and Locate gives me the following error on both demo links (http://domoritz.github.io/leaflet-locatecontrol/demo and https://www.domoritz.de/leaflet-locatecontrol/demo_mapbox):

**Geolocation error: Network location provider at 'https://www.googleapis.com/' : No response received..**

**Comment by 2803media** [comment]
any update on this current problem?

**Comment by domoritz** [comment]
I don't think this problem is related to this plugin but the browser, the os, or leaflet.
