### ISSUE TITLE
Marker icon not centered

### ISSUE THREAD

**Issue by fabiocaccamo** [domoritz/leaflet-locatecontrol#271]
The marker icon is not centered, here a screenshot:

![Schermata 2020-05-19 alle 23 51 06](https://user-images.githubusercontent.com/1035294/82382134-bccc5380-9a2b-11ea-8113-093b02a96164.png)

I'm using the latest version of Leaflet and Firefox.

**Comment by domoritz** [comment]
I don't see the issue on https://www.domoritz.de/leaflet-locatecontrol/demo/. Please provide detailed instructions to reproduce the issue.

**Comment by fabiocaccamo** [comment]
I just followed the README instructions and the control works perfectly, since it seems a css only problem I don't know what I could have done wrong...
