### ISSUE TITLE
Questions/Issues concerning initialZoomLevel

### ISSUE THREAD

**Issue by astridx** [domoritz/leaflet-locatecontrol#273]
I just addd `initialZoomLevel`. 

I understood the parameter in such a way that the zoom is then always as I set it for the parameter.

1. When button is blue (no following), zoom is OK, but map is not centered on position. There is no other way, right
2. When button is orange (following), map is centered on position, but this
time, zoom seems to be set on precision circle again. Is there a possibility to leave the zoom at  `initialZoomLevel`? Am I doing something wrong?
3. If I zoom out, button becomes blue, and map is no more centered. Is there any solution to solve this?

Here is a temporary example: https://monster.astrid-guenther.de/index.php/gpxtrack
This is my code:

```
L.control.locate({
	initialZoomLevel: 17,
	strings: {
		'title': 'Wo bin ich',
	},
	locateOptions: {
		enableHighAccuracy: true,
		watch: true,
	}
}).addTo(mymap);
```

**Comment by domoritz** [comment]
initialZoomLevel should be zoom level that your map goes to when you go to orange. It does not affect where the map is centered. 

I don't quite understand your question but the code for this plugin is pretty simple so you can check https://github.com/domoritz/leaflet-locatecontrol/blob/gh-pages/src/L.Control.Locate.js#L533 and see what it does. It may also help you to set a breakpoint in the developer tools and step through the execution.
