### ISSUE TITLE
The control on iOS doesn't work properly with leaflet 1.7.1

### ISSUE THREAD

**Issue by MickGe** [domoritz/leaflet-locatecontrol#274]
Hello,

_I don't if it comes from __leaflet-locatecontrol__ or __leaflet__._  

On iOS, with __leaflet 1.7.1__, the control button doesn't start to locate.
I had to hold it, like to open in a sub-view. It's not « user-friendly ».

I tried to refactoring my code, but I fix it by downgrade to __leaflet 1.6.0__

_Anyway, thank you for the plug-in._

**Comment by domoritz** [comment]
hmm, sounds like 1.7 changed events. Can you help fix the issue?

**Comment by MickGe** [comment]
I'd like to help. But I'm a basic user... I'm still learning to code.

Maybe the solution could be in the following issue : [Leaflet 1.7.1 causes 2 click events to be emitted by Leaflet Controls in Safari #7255](https://github.com/Leaflet/Leaflet/issues/7255).
Or maybe, it will be fixed with __leaflet 1.7.2__...

It really sounds like a dbclick.

**Comment by domoritz** [comment]
Yep, I'm pretty sure it's https://github.com/Leaflet/Leaflet/issues/7255. I see two calls to onClick, which disabled the control immediately after activating it. It's also happening on desktop.

**Comment by MickGe** [comment]
I'm pretty sure, they will fix it on __leaflet__. 👍

**Comment by domoritz** [comment]
Closing for now as the issue seems to be in Leaflet.
