### ISSUE TITLE
title in strings doesn't work

### ISSUE THREAD

**Issue by sobition** [domoritz/leaflet-locatecontrol#275]
I am trying to set a value to title in strings object of options to change the default UI but it's not working I would like to find out if I am missing out anything

here is my options
```

const locateOptions = {
  position: "bottomright",
  icon: "map-location-icon",
  strings: {
    title: "my current location",
  }
};
```

and here is the component I wrote for locate control

```
class LocateControl extends Component {
  componentDidMount() {
    const { options, startDirectly } = this.props;
    const { map } = this.props.leaflet;

    const lc = new Locate(options);

    lc.addTo(map);

    if (startDirectly) {
      // request location update and set location
      lc.start();
    }
  }

  render() {
    return null;
  }
}


```

**Comment by domoritz** [comment]
What title does the online demo in this repo show doe you?

**Comment by sobition** [comment]
If I get you correctly you mean this part of the code

```
lc = L.control.locate({
    strings: {
        title: "Show me where I am, yo!"
    }
}).addTo(map);

```
But I'm doing the same thing. In my options I'm passing strings exactly as the code said and still not wining

**Comment by domoritz** [comment]
The title shows up when you hover over the control. You can see it in action at https://www.domoritz.de/leaflet-locatecontrol/demo/. Since it works in the demo, the issue must be in your code.

**Comment by sobition** [comment]
@domoritz You are right. I thought it must add a string next to the icon. so I wanted to ask if there is a way to do so
