### ISSUE TITLE
How to add text or HTML for the location button instead of icon

### ISSUE THREAD

**Issue by sobition** [domoritz/leaflet-locatecontrol#276]
![jrQEH](https://user-images.githubusercontent.com/33763156/94350889-cad85380-005f-11eb-8efa-2cd23c5c647a.png)
I want to add a text next to the Icon as seen in the image. The work I did here is just adding a content to the styles but the problem is that the clickable area is just the on the icon. Is there any option to set a text or html tag for locate button

**Comment by domoritz** [comment]
It's not a feature I have focused on. I'd be happy to review a pull request that makes it easier to switch to text.
