### ISSUE TITLE
showCompass is not useful

### ISSUE THREAD

**Issue by wanglin88207056** [domoritz/leaflet-locatecontrol#278]
i set the showCompass true, but it does not work on the pc and only show once on the mobile, when you restart the locate, the compass will disappear , did anyone else had the same problem.

**Comment by domoritz** [comment]
Yes, the compass doesn't work in desktop because there is no compass in desktops. 

Please create a separate issue with steps to reproduce for the phone issues.

**Comment by wanglin88207056** [comment]
thanks
