### ISSUE TITLE
Not working in Safari

### ISSUE THREAD

**Issue by jmodj** [domoritz/leaflet-locatecontrol#280]
When I try your demo: 
https://www.domoritz.de/leaflet-locatecontrol/demo/
the marker don't show up in Safari. Sometimes it shows up after clicking multiple times on the control.
It works fine in Chrome and Firefox.

**Comment by domoritz** [comment]
Strange. It used to work fine. Can you check what's happening by setting breakpoints in the code and steeping through it?

**Comment by jmodj** [comment]
I'm sorry but I have no idea how to do debugging in Safari. 

Your mapbox example works on Safari. 
https://www.domoritz.de/leaflet-locatecontrol/demo_mapbox/ <https://www.domoritz.de/leaflet-locatecontrol/demo_mapbox/>

What is the difference?

**Comment by jmodj** [comment]
I changed from Leaflet 1.7.1 to the previous version 1.7.0 and now locatecontrol works again.

**Comment by domoritz** [comment]
See #274. The issue is leaflet https://github.com/Leaflet/Leaflet/issues/7255.

**Comment by domoritz** [comment]
This fixes it for me

```js
var map = new L.Map('map', {
    tap: false, // ref https://github.com/Leaflet/Leaflet/issues/7255
	...
});
```

**Comment by nekromoff** [comment]
I can confirm this workaround *does* work for Safari. Popups work.

**Comment by modenero** [comment]
this workaround does work in the iOS simulator as well (haven't tested on a physical device).

**Comment by nekromoff** [comment]
I can confirm this works on iOS devices.

**Comment by trainoasis** [comment]
> This fixes it for me
> 
> ```js
> var map = new L.Map('map', {
>     tap: false, // ref https://github.com/Leaflet/Leaflet/issues/7255
> 	...
> });
> ```

Does this have any other negative side-effects normal users on other platforms would be expecting?

**Comment by nekromoff** [comment]
It does not seem to have, both Apple and non-Apple users seem to be able to use map properly.
