### ISSUE TITLE
Start and stop events

### ISSUE THREAD

**Issue by tgelz** [domoritz/leaflet-locatecontrol#281]
I recently added a feature to our Leaflet application that required knowing when the locate control was being activated or deactivated to trigger certain changes in the map's behavior. There currently doesn't seem to be a proper way to achieve this (unless I'm missing something), so I extended the control to be able to fire events.

It would be nice if these events could be added as a standard feature, as extending a control and overriding native functions means you always have to check if something changed after an update.

I placed `this._map.fire('locatestart')` and `this._map.fire('locatestop')` after setting the `_active` flag in the `_activate()` and `_deactivate()` functions respectively, but there might be a better place for these.

**Comment by domoritz** [comment]
Can you use the createButtonCallback and add a click listeners to the link? Or is that not enough?

**Comment by tgelz** [comment]
Unfortunately, that wouldn't be reliable enough as the locate control can (and does) get started and stopped programmatically, not only by our code (e.g. autostart on page load), but also by things like `onLocationOutsideMapBounds` and ` _onLocationError`.

**Comment by domoritz** [comment]
Makes sense. Can you send a pull request?
