### ISSUE TITLE
Compass activation

### ISSUE THREAD

**Issue by yanis-sadeg** [domoritz/leaflet-locatecontrol#285]
Hello,

is it possible to activate the compass manually with code instead of clicking on the button?

Thank you.

**Comment by domoritz** [comment]
You could call [`_onClick`](https://github.com/domoritz/leaflet-locatecontrol/blob/7e0fa72561616e81600b3728bb48e58b8aa38741/src/L.Control.Locate.js#L373) or [`start`](https://github.com/domoritz/leaflet-locatecontrol/blob/7e0fa72561616e81600b3728bb48e58b8aa38741/src/L.Control.Locate.js#L421).

**Comment by Lunok** [comment]
Yes thanks, it's what i already did, but it doesn't active the access the the orientation and motion to show the arrow.

**Comment by yanis-sadeg** [comment]
Thank you for your answer @domoritz . I was already using start() but it doesn't display the arrow of the compass, only the current position with the accuracy indicator around the current position. I also tried _onClick() but the compass is not displayed either. Also, it doesn't even ask for the access to the orientation and motion (on iphone 12), but if i press the button by myself on the screen, it works. 

Any idea?

**Comment by domoritz** [comment]
Hmm, not sure. Maybe you need to bind the element to the function. If you look at https://github.com/domoritz/leaflet-locatecontrol/blob/7e0fa72561616e81600b3728bb48e58b8aa38741/src/L.Control.Locate.js#L358, you can see that we only call `_onClick`. Try stepping through the code with a debugger.

**Comment by yanis-sadeg** [comment]
> 
> 
> Hmm, not sure. Maybe you need to bind the element to the function. If you look at
> 
> https://github.com/domoritz/leaflet-locatecontrol/blob/7e0fa72561616e81600b3728bb48e58b8aa38741/src/L.Control.Locate.js#L358
> , you can see that we only call `_onClick`. Try stepping through the code with a debugger.

Thanks for this answer, I will investigate more and let you know if it works.

**Comment by yanis-sadeg** [comment]
Ok, we just can't do it like this. It need necessary an user gesture to request the permission (webapp).

**Comment by jessegpierce** [comment]
In searching for an answer to this issue, I found this thread located here: [https://developer.apple.com/forums/thread/128376](url).
For my quick solution, I put this snippet at the top of my L.Control.Locate.js file:

`//Request permission to use heading for ios
function requestDeviceOrientation () {
			if (typeof DeviceOrientationEvent !== 'undefined' && typeof DeviceOrientationEvent.requestPermission === 'function') {
				DeviceOrientationEvent.requestPermission()
				.then(permissionState => {
					if (permissionState === 'granted') {
						window.addEventListener('deviceorientation', () => {});
					}
				})
				.catch(console.error);
			} else {
			// handle regular non iOS 13+ devices
			console.log ("not iOS");
			}
		}	`

This requests permission from the user to accept access to the user's device orientation data. Once it loads it gives correct heading on the geolocation icon. Using iPhone 11 Pro Max ios 15.1.

Regards,

Jesse @ northdakotarigsmap dot com
