### ISSUE TITLE
Error when user moves, hides circle

### ISSUE THREAD

**Issue by domoritz** [domoritz/leaflet-locatecontrol#29]
`Uncaught Error: Invalid LatLng object: (40.7999350265614, NaN)`

**Comment by k-anon** [comment]
Unfortunately, this does not fully solve the underlying issue with Leaflet not including the property in the first place in the `locationfound` wrapper events in `Map.Geolocation`. I have tossed a pull request at Leaflet/Leaflet#1889 for their consideration.

**Comment by domoritz** [comment]
@k-anon Great. However, I'll need to keep the fix for compatibility reasons.

**Comment by endigo** [comment]
Hello @domoritz  
I getting this error when i call start() method. Running example is in http://map.minu.mn/beta

here is code: 
var locate = new L.control.locate({
        position: 'bottomleft',
        drawCircle: true,
        icon: 'icon-crosshair',
        iconLoading: 'fa fa-circle-o-notch fa-spin', 
        keepCurrentZoomLevel: true,
        locateOptions: {
            enableHighAccuracy: true,
            maxZoom: 16,
        },
        markerClass: L.marker,
        markerStyle: {
            icon: L.divIcon({
                className: 'mi-marker mi-locate',
                iconSize: [40, 40],
                html: '<span class="icon fa fa-child"></span>'
            }),
            opacity: 1,
        },
        circleStyle: {
            color: '#f1341e',
            fillColor: '#fff',
        }
    });

**Comment by domoritz** [comment]
@ENDiGo Can you create a new issue for this problem and provide a minimum code example that shows the error? Thank you!
