### ISSUE TITLE
FontAwesome 5

### ISSUE THREAD

**Issue by GreenImp** [domoritz/leaflet-locatecontrol#293]
Is there any way of getting this to work with FontAwesome 5? I've tried a few things with limited success.
I'm specifically using FontAwesome 5's VueJs component.

What I thought would work is just enabling the processing of `i` tags, as mentioned here: https://github.com/FortAwesome/vue-fontawesome#processing-i-tags-into-svg-using-font-awesome
And then changing the icon class names to the FontAwesome 5 equivalents.
This partially works, and outputs the correct icon in the initial sate.

However, the icon doesn't get updated with the loading spinner, when it is waiting for permission and finding the location. It also doesn't "highlight" the icon once the position is found.
I think this is because FontAwesome replaces the icon DOM element, with a new `svg` element, and so the class changes don't have an element to modify any more (Or at least not one attached to the DOM).
What I think it needs to do, is to re-build the icon element when the state changes, so it picks up the changes, I think.

Any help would be appreciated.

**Comment by domoritz** [comment]
I won't have time to look into fixing this myself but would be happy to review a pull request.
