### ISSUE TITLE
Create a callback function

### ISSUE THREAD

**Issue by stevevance** [domoritz/leaflet-locatecontrol#3]
On the standard locate function, there's an option to call another function when the location is found and when the location is not found. I have an "onLocationFound" function that runs some custom tasks like building a marker that has a popup with options to save the location among other tasks. 

I thought I could just reference my function in `var onLocationError = function (err) {});` but it's not getting called. 

My custom functions are defined in the HTML after Leaflet and before this plugin.

**Comment by domoritz** [comment]
This works perfectly fine for me.

``` js
map.on('locationfound', function() {
    console.log('foo');
});
```

Reopen the issue if you still can't get it working.
