### ISSUE TITLE
Allow to set speed of "flyTo" animation

### ISSUE THREAD

**Issue by php4fan** [domoritz/leaflet-locatecontrol#302]
I like to enable the `flyTo` option, but the animation is annoyingly slow. I don't see any option to set the speed of the animation.

Ideally there should be several:
- I may want to set a "speed", meaning that panning over a greater distance will take longer
- I may want to set a fixed duration for the animation, meaning that if the distance is greater it should be faster
- some more sophisticated combination of the two, e.g. a desired speed but with a maximum time (so the speed is exceeded if needed to not exceed the max time), or a desired time but with a maximum speed, etc.
- the shape of the "easing" curve: the animation starts slow, accelerates, then slows down at the end. Currently, this is way too much for me. The slowing down at the end is nerve-racking. But obviously no matter how good a default you choose it will never please everybody so it must be configurable
- whether or not to zoom out and then in again and how much. Right now, if the zoom level prior to clicking is lower than the target zoom level (which is usually the case), and almost regardless of the distance, the animation first zooms out, then zooms in again as it pans. The effect is too cartoonish/dramatic. I would like it to not zoom out at all before zooming in. (that's just me, others will have other preferences).
- ......

But at the very, very least, a speed factor and whether or not to zoom back and forth (as opposed to only forth).

**Comment by domoritz** [comment]
This repo is for the leaflet plugin. Please file issues about leaflet in the leaflet repo.

**Comment by php4fan** [comment]
I'm confused. This issue is about the `flyTo` option in the `Control.Locate` plugin.

**Comment by domoritz** [comment]
I think we just pass the option to leaflet and use its default. Is there an option in leaflet to set the speed?
