### ISSUE TITLE
`role="button"` on the control

### ISSUE THREAD

**Issue by Malvoz** [domoritz/leaflet-locatecontrol#307]
`role="button"` should be set using [`setAttribute()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute).

Related: https://github.com/domoritz/leaflet-locatecontrol/pull/269. /cc @Michael-Hanley

**Comment by Malvoz** [comment]
Other resources that you may find helpful:

- [Leaflet guide to accessibility: Test your maps](https://leafletjs.com/examples/accessibility/#test-your-maps)
- [Leaflet Plugin Authoring Guide: Content Accessibility](https://github.com/Leaflet/Leaflet/blob/main/PLUGIN-GUIDE.md#content-accessibility)

**Comment by domoritz** [comment]
Huh, I thought we set it but apparently, we need to use a different API. Thanks for the note.
