### ISSUE TITLE
Icon in dark mode

### ISSUE THREAD

**Issue by Monter** [domoritz/leaflet-locatecontrol#308]
On a phone in Chrome forks with a dark mode (e.g. Adblock browser), the icon becomes invisible after changing the mode - the icon remains black, while other OSM / Leaflet icons can change the colors to light. Is it because of the use of JS and is there any solution?

**Comment by domoritz** [comment]
I made this extension before dark mode was a thing. I would love a pull request to make it compatible with dark mode.

**Comment by Monter** [comment]
If the colors are controlled by JS, it won't be a simple change. You would have to detect the dark mode and replace the colors. It's just an idea, I can't do it.

**Comment by domoritz** [comment]
I think we can set the colors with css. Maybe someone else wants to work on this.
