### ISSUE TITLE
ES module support?

### ISSUE THREAD

**Issue by DavidMStraub** [domoritz/leaflet-locatecontrol#313]
Hi, thanks for this great plugin. I was wondering if you plan to provide an ES module version of it. The [release announcements of Leaflet 1.9.0](https://github.com/Leaflet/Leaflet/releases/tag/v1.9.0) advocate the use of ES modules and it is planned to even remove the `L` global in the future. It would be great if I could just do

```javascript
import leaflet
import leaflet.locatecontrol
```

in the future :slightly_smiling_face:

**Comment by domoritz** [comment]
I'd be happy to accept a pull request for an esm version. The difficulty is that we'd need to set up some compilation process for the non esm version. The benefits are also not as large as with other libraries since the code is so small.
