### ISSUE TITLE
Dropping Mapbox.js support?

### ISSUE THREAD

**Issue by KristjanESPERANTO** [domoritz/leaflet-locatecontrol#324]
I'm tinkering with the dark mode support (for #308) and keep stumbling over the part for _Mapbox.js_.

Since _Mapbox.js_ is no longer being developed and is considered as legacy [[1]](https://docs.mapbox.com/mapbox.js/api/v3.3.1/), I was wondering if we want to drop support in the next version. Projects which still use _Mapbox.js_ could continue to use the old version 0.76.1.

_Mapbox.js_ was Open Source. There is an official but proprietary successor _[Mapbox GL JS](https://docs.mapbox.com/mapbox-gl-js/)_ and an Open Source successor _[MapLibre GL JS](https://maplibre.org/maplibre-gl-js-docs/api/)_. Both successors already have a good locate implementation [[2]](https://docs.mapbox.com/mapbox-gl-js/example/locate-user/)[[3]](https://maplibre.org/maplibre-gl-js-docs/example/locate-user/), so I don't think it would make sense to support the successors.

Before I go to the effort of creating a PR, I wanted to ask what you think of it?

The advantage would be a clearer code that would be easier to maintain.

**Comment by domoritz** [comment]
I wonder whether we can add dark mode support only to the leaflet version? Then we don't have to break the existing mapbox js version. If that's too much hassle, I'm okay with removing support for mapbox.js.

**Comment by KristjanESPERANTO** [comment]
OK, I'll try to keep the support. Thanks for the feedback :slightly_smiling_face:
