### ISSUE TITLE
CSS missing if installing with npm

### ISSUE THREAD

**Issue by ChrisThompsonTLDR** [domoritz/leaflet-locatecontrol#337]
I installed via npm, but it appears that the CSS is not loaded.

All the functionality works, it's just that the CSS and therefore the SVG arrow icon, are missing.

![image](https://github.com/domoritz/leaflet-locatecontrol/assets/348801/67ffe91b-6f18-4e8b-ba3f-b790e2f07a3c)

**Comment by domoritz** [comment]
Please share a listing of your node modules folder for this package. Especially the dist folder.

**Comment by ChrisThompsonTLDR** [comment]
```json
{
    "private": true,
    "scripts": {
        "dev": "vite",
        "build": "vite build"
    },
    "devDependencies": {
        "@alpinejs/focus": "^3.10.5",
        "@tailwindcss/forms": "^0.5.2",
        "@tailwindcss/typography": "^0.5.0",
        "alpinejs": "^3.0.6",
        "autoprefixer": "^10.4.7",
        "axios": "^1.1.2",
        "laravel-vite-plugin": "^0.7.2",
        "postcss": "^8.4.14",
        "tailwindcss": "^3.1.0",
        "vite": "^4.0.0"
    },
    "dependencies": {
        "esri-leaflet": "^3.0.10",
        "esri-leaflet-vector": "^4.1.0",
        "leaflet": "^1.9.4",
        "leaflet.locatecontrol": "^0.79.0",
        "maplibre-gl": "^3.2.0"
    }
}
```

**Comment by domoritz** [comment]
I asked for the folder listing. Not the package file.

**Comment by ChrisThompsonTLDR** [comment]
You just want a screenshot?

![image](https://github.com/domoritz/leaflet-locatecontrol/assets/348801/c1c96870-9357-4892-8a47-34d191e241a5)

**Comment by domoritz** [comment]
Thanks. As you can see the CSS file is there. You need to include it in the HTML file.

**Comment by mauriciabad** [comment]
@domoritz It is there, but it's not documented.

For anyone having this issue, you have to put this code in your project:

```ts
import 'leaflet.locatecontrol'
import 'leaflet.locatecontrol/dist/L.Control.Locate.min.css'
```

I opened a PR adding it to the README https://github.com/domoritz/leaflet-locatecontrol/pull/342
