### ISSUE TITLE
Location error message on iOS only when wifi disabled

### ISSUE THREAD

**Issue by walkhighlands** [domoritz/leaflet-locatecontrol#352]
This is an odd one. This occurs on iOS only, and **only if wifi is disabled**. If your screen is turned off (or phone goes to sleep) with locate active, when you turn the screen back on, you get the KCL Domain Error 0 error message. However, your accurate GPS location is still found once you dismiss the message.

The error message does not occur if wifi is enabled. Is there any way to prevent this seemingly rogue error message on iOS?

**Comment by domoritz** [comment]
This is probably behind this tool since we just use leaflet's/the browser's API to get the location.

**Comment by walkhighlands** [comment]
`onLocationError(err) {
      // ignore time out error if the location is watched
      if (err.code == 3 && this.options.locateOptions.watch) {
        return;
      }`
      
     
I think the problem is that some timeout errors are not giving err.code==3 (as it always works fine after phone has been woken for 5 seconds or so, contrary to my first post I have now seen it when wifi enabled), so I've added a check to the above part of the code so that it also ignores error with 'kCLDomain' message.
