### ISSUE TITLE
Join the discussion: New icon

### ISSUE THREAD

**Issue by domoritz** [domoritz/leaflet-locatecontrol#36]
I noticed that the locate icon is not as obvious as I thought. So, here are two suggestions (old and new one). The new icon is inspired by the icon at http://www.openstreetmap.org/.

Old (normal, located, following):
![locate_old](https://f.cloud.github.com/assets/589034/827182/b1c3c1c0-f097-11e2-8209-22de8cbf1d63.png)

New (normal, located, following):
![locate_new](https://f.cloud.github.com/assets/589034/827299/90db65ba-f099-11e2-8e4b-35c614bf1368.png)

I'd like to know what you think!

**Comment by purplespider** [comment]
New icon looks great! Much more inline to the icons used by Google & Apple Maps, so should be much more obvious to the user.
