### ISSUE TITLE
Accuracy radius

### ISSUE THREAD

**Issue by marcoqu** [domoritz/leaflet-locatecontrol#37]
I coudn't find any references, but I suppose the accuracy value returned by the geolocator is alredy meant to be the displayed as the accuracy _radius_, and not the _diameter_. So you probably shoudn't divide that by 2.
At least that's what Google Maps seems to display.

**Comment by domoritz** [comment]
According to the [w3c specs](http://dev.w3.org/geo/api/spec-source.html) it's "The accuracy attribute denotes the accuracy level of the latitude and longitude coordinates. It is specified in meters and must be supported by all implementations. The value of the accuracy attribute must be a non-negative real number."

Which means that you are right and I have to change this. Good catch!
