### ISSUE TITLE
Feature: stopFollowingOnEvents

### ISSUE THREAD

**Issue by radicalbiscuit** [domoritz/leaflet-locatecontrol#43]
I introduced the `stopFollowingOnDrag` functionality in #22. This has proven to be a very handy feature for our uses, but it has recently come to our attention that one might want following to cancel on any number of events, `dragstart` (or any of the other drage events) being one.

In our local copy, I've written functionality for `stopFollowingOnEvents` into the library. Upon initialization, you declare something like the following in the init options:

```
stopFollowingOnEvents: [
    'dragstart',
    'mousedown',
    'customEvent'
]
```

Inside the library, each item from the provided array is taken and the following-cancellation event handler is bound to it.

This works well. However, we have further customization inserted (awareness of custom events we added into an old version of Leaflet), so I'll have to rework it for a patch, which I'm happy to do.

So, this issue exists in effect to find out if this would be a welcome feature, and if so, what should be done with `stopFollowingOnDrag`. If desired, `stopFollowingOnDrag` could simply become an alias to `stopFollowingOnEvents: ['dragstart']` to preserve backward compatibility.

Anyhow, lemme know. As I said, I'll be happy to make a pull request, but I wanted to see if it'd be welcome, first.

**Comment by domoritz** [comment]
I think this is a great generalization and a welcome future. As you said, we should keep backwards compatibility with `stopFollowingOnDrag` and deprecate and remove it later. The idea with an alias sounds great.  
To deprecate the option, we should add a note to the readme. 

I don't think that I want any specific modification for custom events and such.

**Comment by radicalbiscuit** [comment]
Sounds good. I'll submit a pull request in the next few days.
