### ISSUE TITLE
undef error when clicking spinner

### ISSUE THREAD

**Issue by maximilianloy** [domoritz/leaflet-locatecontrol#47]
When clicking the spinner while first location fix is not yet available I get an undef ref error.

Checking self._event before accessing it fixes it:

diff --git a/src/L.Control.Locate.js b/src/L.Control.Locate.js
index 8f1568f..29cf987 100644
--- a/src/L.Control.Locate.js
+++ b/src/L.Control.Locate.js
@@ -88,7 +88,7 @@ L.Control.Locate = L.Control.extend({
             .on(link, 'click', L.DomEvent.stopPropagation)
             .on(link, 'click', L.DomEvent.preventDefault)
             .on(link, 'click', function() {
-                if (self._active && (map.getBounds().contains(self._event.latlng) || !self.options.setView ||
-                if (self._active && (self._event && map.getBounds().contains(self._event.latlng) || !self.options.setView ||

**Comment by domoritz** [comment]
Hmm, I changed it a bit so that it stops requesting.
