### ISSUE TITLE
Fallback to ip based location

### ISSUE THREAD

**Issue by nikolauskrismer** [domoritz/leaflet-locatecontrol#48]
Wouldn't it be a goof idea to add a fallback to an ip based location if there is nothing else available?

This has been done before by other develops (see https://github.com/onury/geolocator for example).

However, I would suggest to add something like a accuracy_indicator to indicate, that an ip based location is less accurate than a HTML based one (at least usually, isn't it?)

**Comment by domoritz** [comment]
IP based location is probably very approximate so an indicator would definitely be useful. I don't have the time to implement this right now but would accept a pr.

**Comment by nikolauskrismer** [comment]
I just had a look into this in more detail... seems that the needed change should be part of leaflet itself.
The geolocation takes part in file src/map/ext/Map.Geolocation.js. I think the changes should be done in this file...

**Comment by nikolauskrismer** [comment]
I implemented a first working version at https://github.com/nikolauskrismer/Leaflet
Hope this gets merged into master branch :-)

**Comment by domoritz** [comment]
Yes, that totally makes sense. Good luck with the pr.

**Comment by nikolauskrismer** [comment]
Had no luck with my pr. Leaflet is service agnostic (which is not possible when implementing ip based address lookup).

Do you think that ip based lookup should be part of the locatecontrol plugin or a plugin on it's own?

**Comment by domoritz** [comment]
I think this should be a plugin by itself that somehow hacks into the locate call of leaflet or this plugin. I want to keep this plugin light.

**Comment by nikolauskrismer** [comment]
In case someone also needs ip based location:
Have a look at https://github.com/nikolauskrismer/leaflet-locatebyip
