### ISSUE TITLE
Manually enable, disable control

### ISSUE THREAD

**Issue by bmcbride** [domoritz/leaflet-locatecontrol#5]
Is there any way to manually enable and disable this control? I'd like to be able to toggle the locate control from a button outside of the map element. Thanks!

**Comment by domoritz** [comment]
There is no proper way to do that at the moment. However, it should be fairly easy to add. Just make a separate function out of https://github.com/domoritz/leaflet-locatecontrol/blob/gh-pages/src/L.Control.Locate.js#L58 and send me a pull request. As a hack, you could trigger a click on the control.

**Comment by bmcbride** [comment]
Thanks. I'm hoping to have some time to work on this very soon!
