### ISSUE TITLE
How to change the path for the images

### ISSUE THREAD

**Issue by Garito** [domoritz/leaflet-locatecontrol#50]
Hi!
Is there any equivalent L.Icon.Default.imagePath for this plug-in?

What does it do?
It sets a custom path for the images

Now it try to load from the path to the leaflet-locatecontrol css (including it) /images

Thanks!

**Comment by domoritz** [comment]
No, the image paths are set. I'm happy to review a pull request that adds it, though.

**Comment by Garito** [comment]
mmm
I think that it's a problem with the path asked for my system who adds a slashtrash to any url so the relative paths fails to find the resources

In my use case, adding ../ to the images path in the css solves the problem but I don't know if it solves or not the problem in a general way
