### ISSUE TITLE
onLocationFound

### ISSUE THREAD

**Issue by Garito** [domoritz/leaflet-locatecontrol#51]
Is it possible to define a function raise when the location process finish?

In the code I can find onLocationFound that seems the correct place but I don't want to override it and it doesn't call any function or event

Thanks!

**Comment by domoritz** [comment]
Maybe use the `locationfound` event of the map?

**Comment by Garito** [comment]
Yeah!

Usage: map.on('locationfound', function(self) {
  console.log(self);
});

Thanks a lot!
