### ISSUE TITLE
Custom marker

### ISSUE THREAD

**Issue by ghost** [domoritz/leaflet-locatecontrol#53]
Is it possible to set a custom marker instead of the stadard blue dot?

**Comment by domoritz** [comment]
Have a look at the options in https://github.com/domoritz/leaflet-locatecontrol#possible-options. You can change the style but it is actually not an icon but a circle drawn directly. 

I think it would be nice to be able to use a real custom icon. If you want, send me a pull request.

**Comment by chk1** [comment]
Just FYI and anyone searching, here's how I did it:

``` javascript
var iconGreen = {
    iconUrl: 'leaf-green.png',
    shadowUrl: 'leaf-shadow.png',
    iconSize:     [38, 95],
    shadowSize:   [50, 64],
    iconAnchor:   [22, 94],
    shadowAnchor: [4, 62],
    popupAnchor:  [-3, -76]
};

L.control.locate({
    markerClass: L.marker,
    markerStyle: { 
        icon: L.icon( iconGreen ) 
    }
}).addTo(map);
```

[JSFiddle Demo](http://jsfiddle.net/xy0vn487/)

**Comment by domoritz** [comment]
@chk1 Awesome. I just created a label for issues with solutions like yours!
