### ISSUE TITLE
When NOT using coords 4326 - fail to get correct bounds

### ISSUE THREAD

**Issue by coomsie** [domoritz/leaflet-locatecontrol#54]
Under

```
var visualizeLocation = function() {
```

the fitBounds sets the wrong bounds for the map if not in 4326 and in local country  circuit.

```
//  map.fitBounds(self._event.bounds, { padding: self.options.circlePadding });
```

But if you use panTo it works to get to the correct place?

```
map.panTo(self._event.latlng);
```

**Comment by coomsie** [comment]
It seems to have something to do with the padding option that sets a point.

I've changed my code to this to sort my problem out .. hopefully help someone else.

```
map.fitBounds(self._event.bounds, {maxZoom: map.getMaxZoom() });
```

**Comment by domoritz** [comment]
Hmm, looks like a bug in Leaflet because all I do is just passing the padding to http://leafletjs.com/reference.html#map-fitbounds

**Comment by coomsie** [comment]
agreed, same conclusion I came to ..
