### ISSUE TITLE
stopLocate if isOutsideMapBounds()

### ISSUE THREAD

**Issue by Rikaelus** [domoritz/leaflet-locatecontrol#56]
I was having an issue in that if the user is outside the map bounds the appropriate method would be called, but the user had to click the locate button "off" before being able to try the operation again.

It looks like maybe this is intended to be solved here:

``` js
        L.DomEvent
            .on(link, 'click', L.DomEvent.stopPropagation)       
            .on(link, 'click', L.DomEvent.preventDefault)
            .on(link, 'click', function() {
                if (self._active && (self._event === undefined || map.getBounds().contains(self._event.latlng) ||$
                    isOutsideMapBounds())) {               
                    stopLocate();
                } else {
                    locate();
                }
            })           
            .on(link, 'dblclick', L.DomEvent.stopPropagation);

To get the expected behavior I added this, though:
                if (isOutsideMapBounds()) {
                    self.options.onLocationOutsideMapBounds(self);
=>                    stopLocate();
                } else {
                    map.fitBounds(self._event.bounds, {
                        padding: self.options.circlePadding,
                        maxZoom: self._locateOptions.maxZoom
                    });
                }
```

You might have a better fix for this but wanted to let you know.

**Comment by domoritz** [comment]
Hmm, can you describe a way to reproduce the problem? I don't quite understand it.

**Comment by Rikaelus** [comment]
I just sent a URL to the email address listed on your site. It might be on the web but no point in advertising to the world...

Anyway. If you click on the control you'll get a popup saying you're outside the boundaries, but you'll notice the control remains enabled. You need to turn it "off" before you can try again. My belief is that it shouldn't even turn "on" on failure.

Point of comparison, you call stopLocate() explicitly in your onLocationError function, so it's accounted for in that case. Just not when it "succeeds" but is out of bounds.

**Comment by domoritz** [comment]
Ahh, I see. Actually, you could just add something to the callback `onLocationOutsideMapBounds` instead of changing the library code. 

For example:

``` js
onLocationOutsideMapBounds: function(context) {
    context.stopLocate();
    alert(context.options.strings.outsideMapBoundsMsg);
}
```

The reason why I didn't add it in the first place is that you might not want to call `stopLocate` and wait for the user to return into the map boundaries. 

Anyway, good catch and I'll add a call to `stopLocate` to the default callback implementation.
