### ISSUE TITLE
Enhancement Request: onLocationFound

### ISSUE THREAD

**Issue by Rikaelus** [domoritz/leaflet-locatecontrol#57]
As an advanced option it might be nice if we could override the default locationfound logic with an onLocationFound option.

The bosses are pushing an idea that would require a more complex boundary detection algorithm (based on a polygon rather than the Leaflet map boundaries) and I'd need to apply any such logic at that level.

I do realize this would negate some of the functionality included in this software but it'd still be nice to use for the remaining pieces (control, following, etc.)

**Comment by domoritz** [comment]
Since I don't know about your requirements, why don't you add it and send a pull request which we then can discuss?

**Comment by wraybowling** [comment]
I second this request. I just ran into a need for being able to parse the data that results from the location found event. In my particular case, I'm going to push the resulting lat/long through the mapbox geocoder so i can display country/province/city.

Since Locate is being created with L.Control.extend() then I guess we should see how things like the geocoder enable the .on() function so events like 'found' fire events.

**Comment by domoritz** [comment]
@wraybowling in your case, you can just subscribe to the location found even on the map. It sounds like to don't want to change the logic of the locate control.

**Comment by wraybowling** [comment]
Could you provide an example? I thought I understood what you meant, but then I broke my fiddle. http://jsfiddle.net/rgbk/JgmE3/11/

**Comment by gmccrackin** [comment]
I'm not sure if you figured this out or not. So I will try to help if I can.

You had:

```
var map = L.mapbox.map('map', mapboxString)
          .addControl(
                L.mapbox.geocoderControl(mapboxString, {})
                .on('select',displayResults)
                .on('found',displayResults)
            )
            .addControl(
                L.control.locate().on('found', displayResults)
            )
;
```

I believe you want:

```
var map = L.mapbox.map('map', mapboxString)
          .addControl(
                L.mapbox.geocoderControl(mapboxString, {})
                .on('select',displayResults)
                .on('found',displayResults)
            )
            .addControl(
                L.control.locate()
            ).on('locationfound', displayResults)
;
```

This is because the event fires on the map object not the locate control. Hopefully this was helpful.

**Comment by domoritz** [comment]
Thanks @gmccrackin. I'm not sure what the right thing is so I fired the events on the map. If that is not the standard, it might be worth changing.

**Comment by gmccrackin** [comment]
Yeah I think firing it on the map is the standard for this.
