### ISSUE TITLE
Retina icon

### ISSUE THREAD

**Issue by tmcw** [domoritz/leaflet-locatecontrol#58]
Right now there's a `@1x` icon & SVG files. Should be a pretty quick task to render out a `@2x` icon for this. Will do when I get a moment.

**Comment by domoritz** [comment]
Yes, since there is the SVG file it should be straightforward. The different colors are in layers and I used Inkscape to create the SVG.

**Comment by domoritz** [comment]
Why not generate a web font with vector versions and even animate the spinner using CSS? This would allow even setting the color of the icons.

**Comment by tmcw** [comment]
I would rather go for the simple way first :)

**Comment by domoritz** [comment]
Agreed. But would be nice anyway. I could look into web fonts as I don't have a retina device and never created retina icons. Could you render the `@2x` icon and send a pr? Thanks!

**Comment by tmcw** [comment]
Yep, https://github.com/domoritz/leaflet-locatecontrol/pull/59

**Comment by tmcw** [comment]
Thx for merging - can you tag a release and I'll update the [cdn](https://www.mapbox.com/mapbox.js/plugins/#leaflet-locatecontrol)?

**Comment by domoritz** [comment]
Thanks. I merged it and tagged it as https://github.com/domoritz/leaflet-locatecontrol/releases/tag/v0.24.0. Also, there is a new version with icon fonts and animation in css in https://github.com/domoritz/leaflet-locatecontrol/releases/tag/v0.25.0.

Could you link me to the CDN so that I can add it to the readme? It would be good if people could just copy and paste some html to get it working without having to download the files.

**Comment by domoritz** [comment]
Oh, I just saw the link ;-) Is there a way to update the CDN automatically?

**Comment by domoritz** [comment]
@tmcw I'd like to update the mapbox CDN. Currently this control is on version 41 but mapbox only has version 24.

**Comment by tmcw** [comment]
If you pull-request [adding the files to the mapbox.js-plugins repo](https://github.com/mapbox/mapbox.js-plugins/tree/master/plugins/leaflet-locatecontrol) I can run the deploy script.

**Comment by domoritz** [comment]
Thanks! That was what I was looking for.

**Comment by domoritz** [comment]
I sent a pr https://github.com/mapbox/mapbox.js-plugins/pull/24. I don't know whether you want the full font awesome, though.

**Comment by tmcw** [comment]
:+1: just deployed 0.42 and updated the site to point to it.
