### ISSUE TITLE
e.latlng.lng instead of e.latlng.lon

### ISSUE THREAD

**Issue by JohnCLo** [domoritz/leaflet-locatecontrol#6]
Hi,

Just a minor syntax error on line 80 for the onLocationFound function... should be e.latlng.lng instead of e.latlng.lon

Cheers

**Comment by domoritz** [comment]
Thank's for pointing that out! It hasn't been noticed because if the longitude changes, the latitude normally changes as well. Nonetheless, I'm glad you found it.
