### ISSUE TITLE
Enhancement request: keep current map zoom level when located

### ISSUE THREAD

**Issue by gitare** [domoritz/leaflet-locatecontrol#60]
The maxZoom level is used when the location. Is it possible to add an option to choose to keep the current map zoom level?

This is actually quite simple :
- In locateOptions, add a useCurrentZoomLevel option:
  locateOptions: {
  useCurrentZoomLevel : true,
  }
- In the visualizeLocation() function, add a check to this option in fitBound when setting the maxZoom, and get the current zoom level if needed :
  maxZoom: self._locateOptions.useCurrentZoomLevel?map.getZoom():self._locateOptions.maxZoom

(Sorry, I don't know how to do a pull request)

Maybe it's related to https://github.com/domoritz/leaflet-locatecontrol/issues/23

Thanks.

**Comment by domoritz** [comment]
Sounds very useful. Could you try to make a pull request? There is good documentation at https://help.github.com/articles/fork-a-repo

**Comment by gitare** [comment]
The pull request is done. Thanks for the doc!
