### ISSUE TITLE
Bower package

### ISSUE THREAD

**Issue by sroze** [domoritz/leaflet-locatecontrol#62]
I plan to create an AngularJS module that integrates your `leaflet-locatecontrol` with `angular-leaflet-directive` but it would be great to simply have a bower package for your library.

Can you create one ? Also, I think that it would be better to store sources in a `master` branch and the demonstration in `gh-pages` branch... And it will be a little bit easier to create the bower package ;-)

**Comment by nikolauskrismer** [comment]
http://bower.io/search/?q=leaflet-locatecontrol tells us that there is a bower-package registered.
I am struggling on using it, since there is no "dist" package with one merged css file (the project uses css import statements).

**Comment by domoritz** [comment]
He... I did not create that but I am happily accepting contributions :-P

**Comment by nikolauskrismer** [comment]
I played a bit around with bower and grunt, so the plugin becomes easier to use.
However, the grunt fails when combining the css (seems to be related with the wuff files).

Is there another (easy/automated) way to create a single css file for this project (so I could use it and send a PR)?

**Comment by domoritz** [comment]
I don't know about packaging js libs. Sorry. But I'm sure people have had this issue before so there must be something on the internet.

**Comment by domoritz** [comment]
Done ;-) Took a while, I know.

**Comment by sroze** [comment]
:+1:

**Comment by nikolauskrismer** [comment]
Did you solve my css concatination issue?
Does your solution create a single css file (could not find anything like a Gruntfile or similar in the repository)?

Does one have to include the css file when using the bower package?
