### ISSUE TITLE
An external locate button

### ISSUE THREAD

**Issue by plisvb** [domoritz/leaflet-locatecontrol#67]
Hi, great plugin, I was just wondering if the "locate functionality" can be invoked by a button outside of the map.  I'd like to make it more obvious for my users.

**Comment by domoritz** [comment]
Have a look at https://github.com/domoritz/leaflet-locatecontrol#methods

**Comment by plisvb** [comment]
thanks for that, I got it to work but I don't know how to add some of the options?

```
function locateUser() {
    this.map.locate({setView : true});
```

}

how do I add keepCurrentZoomLevel: false? and locateOptions: {maxZoom: 15}

tried  

function locateUser() {
        this.map.locate({setView : true, keepCurrentZoomLevel: false});
}

but no luck

**Comment by domoritz** [comment]
You have to set the options when you create the locate control. See https://github.com/domoritz/leaflet-locatecontrol#possible-options.

**Comment by gmccrackin** [comment]
@plisvb Did you figure this out?
I know its from a while ago but I thought I should comment just in case.

I think there is some confusion here.

You are calling the locate method on the map object. Which you don't want to do.
Instead you should be calling the locate method on the control object.
