### ISSUE TITLE
Strange behaviour on iPhone 

### ISSUE THREAD

**Issue by gelinger777** [domoritz/leaflet-locatecontrol#68]
I am trying to use your script in mobile app built on Rhomobile. Everything works perfect, Only when location icon is drawn your icon just disappears from control. Any ideas why? 

http://oi60.tinypic.com/10mls9f.jpg 

???

**Comment by domoritz** [comment]
Hmm, no idea. Can you see whether all images are accessible. Do you use the latest version with the icon font? In that case if you can see the original icon, you should be able to see it when it's active because I only change the color.

**Comment by gelinger777** [comment]
I changed the setting of image to icon-direction and it works now. Maybe some file-cashing issue. Closing ticket. Thanks

**Comment by domoritz** [comment]
I noticed a bug in the readme. it should say `icon-location`, not `icon-locate`. The default was correct, though.

**Comment by gelinger777** [comment]
yeah, seems that was problem. just fix it fur future dudes like me :)))

**Comment by domoritz** [comment]
My mistake. It's fixed. Thanks for reporting the issue and using my library.
