### ISSUE TITLE
Issues between this control and awesome-markers

### ISSUE THREAD

**Issue by maggix** [domoritz/leaflet-locatecontrol#69]
Hello, if I use this Leaflet plugin with another plugin called Awesome-Markers (https://github.com/lvoogdt/Leaflet.awesome-markers), the Fontawesome icons within the Leaflet markers don't show anymore.

Solution for me was to comment out the following lines from `L.control.locate.css`:

```
@import url('font/locate-fa.woff');
@import url('css/locate-fa.css');
```

No issues were displayed on Chrome console, though. This took me some trial-and-error.

**Comment by bradparks** [comment]
I too have found this issue.... and tried the above suggested fix, and it didn't seem to help. Any suggestions?

**Comment by bradparks** [comment]
it seems like it's nearly fixed if I replace any css references to `[class^="icon-` with `[class^="icon-location`, but the animation icon appears off still... all other state icons seem fine...

**Comment by redheli** [comment]
@bradparks thank you. I also replace [class*=" icon-"

**Comment by billyburly** [comment]
the suggestion by @maggix worked for me

**Comment by domoritz** [comment]
Alright, looks like this issue has come up a couple of times and should be fixed. I am quite busy right now but can review pull requests. Otherwise you'll need to wait. Sorry.
