### ISSUE TITLE
icon-location and icon-direction doesn't show in Android default browser

### ISSUE THREAD

**Issue by bruha** [domoritz/leaflet-locatecontrol#78]
icon-location and icon-direction doesn't show in Android default browser
![screenshot_2014-07-15-14-00-21](https://cloud.githubusercontent.com/assets/540457/3584385/2f67d1b0-0c18-11e4-8682-f8869182358a.png)
![screenshot_2014-07-15-14-00-38](https://cloud.githubusercontent.com/assets/540457/3584386/2f6affd4-0c18-11e4-9829-e748321e77ee.png)

**Comment by domoritz** [comment]
Hmm, interesting. It works on mobile chrome. Can you find out what's going wrong?

**Comment by cebe** [comment]
I have the same issue. Any idea how to debug this?

**Comment by domoritz** [comment]
It might be an issue with the icon font. I guess the default browser has problems with icon fonts. Unfortunately, I cannot debug this further so I need to rely on your help. If you don't want to debug but just have a working version, you can use an old version of my plugin without the icon font.

**Comment by cebe** [comment]
thanks for your answer, I played around with android debugging tools but could not figure out the cause.

**Comment by domoritz** [comment]
I found something on the internet about the `text-rendering: auto;` style. Maybe you can find something helpful.

**Comment by cebe** [comment]
looks like there is not much you can do about this except adding a huge bunch of extra javascript... http://stackoverflow.com/questions/11991052/font-awesome-does-not-work-on-android-browser

**Comment by cebe** [comment]
found a better solution, sent a PR.
