### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by DrYSG** [domoritz/leaflet-locatecontrol#83]
Any hope on getting this as an npm package? 
(I see an issue about getting this with bower, But I struggle more with bower than npm, and I don't mind grunting to strip out items).

here are two links to describe the process:

http://decodize.com/javascript/build-nodejs-npm-installation-package-scratch/

http://www.mattpalmerlee.com/2013/04/23/create-your-first-node-module-and-publish-it-to-the-npm-registry/

**Comment by domoritz** [comment]
I added bower. Looks like it's the standard for js + css stuff. If you feel npm should be added as well, reopen.

**Comment by DrYSG** [comment]
If you don't mind npm, it would be useful. Yes, I like the theory of bower, but it is much poorer in handing our firewall, so I need a different method, and since I do a lot of node stuff, npm works quite well (and is integrated into VS2013).

I think the same package.json will work for npm.
