### ISSUE TITLE
locateOptions overwritten, spinner not rotating...

### ISSUE THREAD

**Issue by celoftis** [domoritz/leaflet-locatecontrol#87]
On Android 4.1.2, using the latest control (i.e, targeting leaflet 0.7.0+)
- When I instantiate a locate control the default `locateOptions: {maxZoom : Infinity, watch : true}` are being completely overwritten with the locateOptions I provide. For example, when I create the locate control like this

``` javascript
lc = L.control.locate({
        position : 'bottomright',
        follow : true,
        stopFollowingOnDrag : true,
        metric : false,
        strings : {
            title : 'Show Position',
            popup : 'You are within {distance}{unit} of this location',
            outsideMapBoundsMsg : 'You appear to be located outside the boundaries of the map'
        },
        locateOptions : {
            frequency : 500,
            enableHighAccuracy : true,
            maximumAge : 5000
        }
    }).addTo(map);
```

the default `locateOptions: {maxZoom : Infinity, watch : true}` are completely overwritten with `{frequency : 500, enableHighAccuracy : true, maximumAge : 5000}` versus being merged. Because of this, the `watch` option is not longer defined so after calling lc.locate() location timeouts (`onLocationError`) cause the location watch to be cancelled, i.e., `stopLocation()` is called. 

I was able to to work around this by passing `{watch : true}` in with the original instantiation of the locate control, but it seems hackish - am I doing something wrong? Is there a way to get the locateOptions to merge (I didn't have to do this for the L.Control.Locate compatible with leaflet 0.6.4)?
- While listening for locations, the spinner is not rotating...

**Comment by domoritz** [comment]
Wow, I'm impressed that this error hasn't come up earlier. In fact, the whole options merging is broken and every nested object was overridden. Can you test it again?

**Comment by celoftis** [comment]
Not quite working - sub options (i.e., locateOptions) are being merged, but other top level items, e.g., position, are not being overridden. 

Ultimately, I suppose Leaflet should include a method like [jQuery's deep extend](http://api.jquery.com/jquery.extend/#jQuery-extend-deep-target-object1-objectN), but until then, I added this to 'src/L.Control.Locate.js' to merge options 1-level deep, seems to work OK:

``` javascript
for (var i in options) {
    if (typeof options[i] === 'object') {
        L.extend(this.options[i], options[i]);
    } else {
        this.options[i] = options[i];
    }
}
```
