### ISSUE TITLE
update  mapbox CDN

### ISSUE THREAD

**Issue by redheli** [domoritz/leaflet-locatecontrol#88]
Can update the latest version to mapbox CDN? 

current mapbox CDN link :

<script src='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.24.0/L.Control.Locate.js'></script>

<link href='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.24.0/L.Control.Locate.css' rel='stylesheet' />

It dont have function like "keepCurrentZoomLevel".

thx

**Comment by domoritz** [comment]
I don't control it. Please talk to mapbox about updating their CDN. As an alternative, you can use the bower package I provide.
