### ISSUE TITLE
Locate spinner icon not rotating

### ISSUE THREAD

**Issue by celoftis** [domoritz/leaflet-locatecontrol#89]
On Android 4.1.2,
The locate spinner icon is not spinning while the locate command is waiting for a response from the GPS radio.

**Comment by domoritz** [comment]
Cannot confirm. Can you give me some more details about this bug?

**Comment by celoftis** [comment]
I'm building a PhoneGap app, I have upgraded my app to include leaflet to 7.0.3 and the latest version of your locate control. 

When testing on Android 4.1.2 or 4.2.2 the locate-fa spinner does not animate/rotate while the device waits (listens) for a response from the GPS radio...

**Comment by domoritz** [comment]
Can you try the latest version with the new icons and improved code?

**Comment by celoftis** [comment]
Its going to be a while before I can climb back into this code... I'll let
you know when I give it a test.
