### ISSUE TITLE
Options are not being read in version 0.7.3

### ISSUE THREAD

**Issue by nickdos** [domoritz/leaflet-locatecontrol#91]
I've been trying to set some options as per the docs and they are not being picked up with version 0.7.3. If I use the version in [Mapbox CDN](https://www.mapbox.com/mapbox.js/plugins/#leaflet-locatecontrol), (v0.24.0) then they are picked up as expected.

My code is:

```
L.control.locate({position:'topright'}).addTo(map);
```

Icon is still being shown on the left/top.

**Comment by nickdos** [comment]
Here's a jsfiddle: http://jsfiddle.net/nickdos/8kn1g8cq/1/

**Comment by domoritz** [comment]
Yes, I messed up the options initialization.
