### ISSUE TITLE
Spinner still rotating in Firefox if security prompt is closed

### ISSUE THREAD

**Issue by tonprince** [domoritz/leaflet-locatecontrol#93]
The spinner icon is still rotating if the user cancels the prompt dialog or denies sharing the user location.

It seams Firefox doesn't fire error callback.

**Comment by domoritz** [comment]
Yes, I believe that is a bug in Firefox. I see the same behaviour in this example https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation#Live_Result

**Comment by nikolauskrismer** [comment]
Just came across this FF issue describing the problem in more detail:
https://bugzilla.mozilla.org/show_bug.cgi?id=675533

@domoritz :
Wouldn't the link you posted describe a FF-browser-hack solution (in the "Prompting for permission" section). Have you ever tried this?

**Comment by domoritz** [comment]
@nikolauskrismer I have not tried it. I also don't see how I could integrate that with leaflet's locate function. To be honest, I also don't think it's worth putting a really bad hack into this plugin.

**Comment by nikolauskrismer** [comment]
@domoritz
Yes... that's also the way I think about it.
Just wanted to ask if you tried it because I'm unsure if it would work :-)

**Comment by alx77** [comment]
Is it tested for Android? I trying demo with Chrome and Dolphin and have no success :(

**Comment by domoritz** [comment]
Just tested chrome and Firefox on Android without any problems. Can you go
to http://domoritz.de/leaflet-locatecontrol/demo/ and see if there are any
errors in the console?
