### ISSUE TITLE
iOS 8 broken

### ISSUE THREAD

**Issue by maximilianloy** [domoritz/leaflet-locatecontrol#94]
Open the demo in iOS 8.0 Safari. After agreeing to share the location an error popup is shown as in the screenshot and no location is set:

![bildschirmfoto 2014-09-27 um 11 46 55](https://cloud.githubusercontent.com/assets/6249264/4430364/709d2df4-462b-11e4-8e68-151d7d16f298.png)

**Comment by domoritz** [comment]
https://stackoverflow.com/questions/1409141/location-manager-error-kclerrordomain-error-0

Reopen if you still think it's an error of the plugin.
