### ISSUE TITLE
Dis

### ISSUE THREAD

**Issue by thienbao92** [domoritz/leaflet-locatecontrol#95]
I'm having the issue that in browser (Firefox), the switch between start and stop following location in control button works very well, but when I make application running on Android using Ionic platform, it just process one time and when I re-drag the map, the button just appear as locate, not start following anymore. 

It will be nice if you guys could help me with that issue. I'm really appreciate that!!!

**Comment by domoritz** [comment]
Sorry, I have never used Ionic and cannot help here.

**Comment by thienbao92** [comment]
HI domoritz,

thanks for you reply! Finally, I figured out how to to that! Hope somebody can use it later. 

http://ionicframework.com/docs/api/page/tap/

just need to add <div data-tap-disabled="true" before the div map
