### ISSUE TITLE
Add TopLeft and BottomRight padding

### ISSUE THREAD

**Issue by ghost** [domoritz/leaflet-locatecontrol#97]
On my app for fitBounds I'm using paddingTopLeft and paddingBottomRight options (to add padding only on the left side of the screen).

When using your control, I cannot seem to find a way of adding this kind of padding, it always makes it in a centre of a map. Would it be possible to integrate it in the next release?

**Comment by domoritz** [comment]
You can pass in the `circlePadding`. It is passed directly to fitBounds. See its documentation at http://leafletjs.com/reference.html#map-fitboundsoptions
